import { CommonSchema } from './common_schema';

const esIndex = 'shapetracts_flat';

const AcerageSummaryMeta = {
	esIndex,
	isElasticQuery: false,
	pageSize: 25,
	pagination: {
		pageIndex: 0,
		pageSize: 25,
	},
	defaultSort: { field: '_ts', order: 'asc' },
	maxTableHeight: 'calc(100vh - 350px)',
	isInFiniteScroll: true,
	columnVirtualization: false,
	TableSchema: [
		{
			...CommonSchema.HIDDEN,
			name: 'id',
			accessorKey: 'id',
		},

		{
			...CommonSchema.HIDDEN,
			name: '_id',
			accessorKey: '_id',
		},
		{
			...CommonSchema.COMMON_COLUMN,
			name: 'state',
			accessorFn: row => row?.state,
			id: 'state',
			header: 'State',
			isGrouped: true,
		},
		{
			...CommonSchema.COMMON_COLUMN,
			name: 'county',
			accessorFn: row => row?.county,
			id: 'county',
			header: 'County',
		},
		{
			...CommonSchema.COMMON_COLUMN,
			name: 'prospect',
			accessorFn: row => row?.shape?.shapeJson?.properties?.prospectID,
			id: 'shape.shapeJson.properties.prospectID',
			header: 'shape.shapeJson.properties.prospectID.keyword',
		},
		{
			...CommonSchema.COMMON_COLUMN,
			name: 'shape.shapeJson.properties.report.devReportGrossAcres',
			type: 'number',
			accessorFn: row => row?.shape?.shapeJson?.properties?.report?.devReportGrossAcres,
			id: 'shape.shapeJson.properties.report.devReportGrossAcres',
			header: 'Report Dev Gross',
			...CommonSchema.AGGREGATED_FIELD('Report Dev Gross'),
		},
		{
			...CommonSchema.COMMON_COLUMN,
			name: 'shape.shapeJson.properties.report.devReportNet',
			type: 'number',
			accessorFn: row => row?.shape?.shapeJson?.properties?.report?.devReportNet,
			id: 'shape.shapeJson.properties.report.devReportNet',
			header: 'Report Dev Net',
			...CommonSchema.AGGREGATED_FIELD('Report Dev Net'),
		},
		{
			...CommonSchema.COMMON_COLUMN,
			name: 'shape.shapeJson.properties.report.devCompanyNetAcres',
			type: 'number',
			accessorFn: row => row?.shape?.shapeJson?.properties?.report?.devCompanyNetAcres,
			id: 'shape.shapeJson.properties.report.devCompanyNetAcres',
			header: 'Dev Co Net',
			...CommonSchema.AGGREGATED_FIELD('Dev Co Net'),
		},
		{
			...CommonSchema.COMMON_COLUMN,
			name: 'shape.shapeJson.properties.report.undevReportGrossAcres',
			type: 'number',
			accessorFn: row => row?.shape?.shapeJson?.properties?.report?.undevReportGrossAcres,
			id: 'shape.shapeJson.properties.report.undevReportGrossAcres',
			header: 'Report Undev Gross',
			...CommonSchema.AGGREGATED_FIELD('Report Undev Gross'),
		},
		{
			...CommonSchema.COMMON_COLUMN,
			name: 'shape.shapeJson.properties.report.undevReportNet',
			type: 'number',
			accessorFn: row => row?.shape?.shapeJson?.properties?.report?.undevReportNet,
			id: 'shape.shapeJson.properties.report.undevReportNet',
			header: 'Report Undev Net',
			...CommonSchema.AGGREGATED_FIELD('Report Undev Net'),
		},
		{
			...CommonSchema.COMMON_COLUMN,
			name: 'shape.shapeJson.properties.report.undevCompanyNetAcres',
			type: 'number',
			accessorFn: row => row?.shape?.shapeJson?.properties?.report?.undevCompanyNetAcres,
			id: 'shape.shapeJson.properties.report.undevCompanyNetAcres',
			header: 'Undev Co Net',
			...CommonSchema.AGGREGATED_FIELD('Undev Co Net'),
		},
		{
			...CommonSchema.COMMON_COLUMN,
			name: 'shape.shapeJson.properties.report.reportGrossAcres',
			type: 'number',
			accessorFn: row => row?.shape?.shapeJson?.properties?.report?.reportGrossAcres,
			id: 'shape.shapeJson.properties.report.reportGrossAcres',
			header: 'Total Report Gross',
			...CommonSchema.AGGREGATED_FIELD('Total Report Gross'),
		},
		{
			...CommonSchema.COMMON_COLUMN,
			name: 'shape.shapeJson.properties.report.reportNet',
			type: 'number',
			accessorFn: row => row?.shape?.shapeJson?.properties?.report?.reportNet,
			id: 'shape.shapeJson.properties.report.reportNet',
			header: 'Total Report Net',
			...CommonSchema.AGGREGATED_FIELD('Total Report Net'),
		},
		{
			...CommonSchema.COMMON_COLUMN,
			name: 'shape.shapeJson.properties.report.companyNetAcres',
			type: 'number',
			accessorFn: row => row?.shape?.shapeJson?.properties?.report?.companyNetAcres,
			id: 'shape.shapeJson.properties.report.companyNetAcres',
			header: 'Total Co Net',
			...CommonSchema.AGGREGATED_FIELD('Total Co Net'),
		},
	],
};

export default AcerageSummaryMeta;
