
export const CommonSchema = {
	COMMENTS: {
		name: 'comments',
		accessorKey: 'comments',
		header: '',
		size: 120,
		isPinned: false,
		hidden: false,
		filter: false,
		isSearchField: false,
		enableSorting: false,
		type: 'string',
		enableColumnActions: false,
		enableHiding: false,
		enableColumnFilter: false,
		enableColumnOrdering: false,
		enableResizing: false,
		showInLast: true,
	},
	TAGS: {
		name: 'tags.tag.keyword',
		accessorKey: 'tags.tag',
		header: 'Tags',
		size: 250,
		isPinned: false,
		hidden: false,
		filter: true,
		isSearchField: true,
		enableSorting: true,
		type: 'string',
		enableColumnActions: false,
		enableColumnOrdering: false,
		enableResizing: false,
		showInLast: true,
	},
	HIDDEN: {
		header: ' ',
		isSearchField: false,
		hidden: true,
		enablePinning: false,
		enableHiding: false,
		enableColumnActions: false,
		enableColumnOrdering: false,
		enableSorting: false,
	},
	MONGO_ID: {
		header: 'M1neral System ID',
		isSearchField: false,
		hidden: true,
		enableColumnFilter: false,
		enablePinning: false,
		enableColumnActions: false,
		enableColumnOrdering: false,
		enableSorting: false,
		size: 250,
		isHiddenFieldExport: true,
	},
	INITAIL_PINNED: {
		isPinned: true,
		enableHiding: false,
		filter: true,
		type: 'string',
		isExternalFilter: false,
		enableColumnActions: true,
		enableColumnOrdering: false,
		size: 350,
	},
	COMMON_COLUMN: {
		size: 250,
		isPinned: false,
		hidden: false,
		filter: true,
		isSearchField: true,
		enableSorting: true,
		type: 'string',
	},
	ACTION_COLUMN: {
		header: ' ',
		isPinned: false,
		hidden: false,
		filter: true,
		isSearchField: false,
		enableSorting: true,
		enableColumnActions: false,
		enableHiding: false,
		type: 'string',
		enableColumnFilter: false,
		enableColumnOrdering: false,
		enableResizing: false,
		showInLast: true,
	},
	SELECT_SOME: {
		name: 'over-ride-checkbox',
		accessorKey: 'over-ride-checkbox',
		isPinned: true,
		hidden: false,
		isSearchField: false,
		enableHiding: false,
		enableSorting: false,
		filter: false,
		isExternalFilter: false,
		enableColumnActions: false,
		enableColumnOrdering: false,
		enableColumnFilter: false,
		enableResizing: false,
		size: 80,
	},
};
