// Summary field keys and  there eskeys
export const customLayersFieldAccessors = {
	Units: {
		keys: [
			{ label: 'County', value: 'shapeJson.properties.originalProperties.County.keyword' },
			{ label: 'State', value: 'shapeJson.properties.originalProperties.State.keyword', orKey: 'StateAbbreviation' },
			{ label: 'Survey/ Meridian', value: 'shapeJson.properties.originalProperties.surveyMerdian.keyword' },
			{ label: 'Block/ Township', value: 'shapeJson.properties.originalProperties.blockTownship.keyword' },
			{ label: 'Range/ Section', value: 'shapeJson.properties.originalProperties.rangeSection.keyword' },
			{ label: 'Abstract/ Section', value: 'shapeJson.properties.originalProperties.abstractNameShortName.keyword' },
			{ label: 'Unit Type', value: 'shapeJson.properties.uType.keyword' },
			{ label: 'Unit Status', value: 'shapeJson.properties.uStatus.keyword' },
			{ label: 'Current Operator', value: 'shapeJson.properties.uPrimaryOperator.keyword' },
			{ label: 'Qualifier', value: 'shapeJson.properties.qualifier.name.keyword' },
			{ label: 'Reviewer', value: 'shapeJson.properties.reviewer.name.keyword' },
			{ label: 'Primary Bench', value: 'shapeJson.properties.uPrimaryBench.keyword' },
		],
		layerKey: 'Unit',
	},
	Parcels: {
		keys: [
			{ label: 'County', value: 'shapeJson.properties.originalProperties.County.keyword' },
			{ label: 'State', value: 'shapeJson.properties.originalProperties.State.keyword', orKey: 'StateAbbreviation' },
			{ label: 'Survey/ Meridian', value: 'shapeJson.properties.originalProperties.surveyMerdian.keyword' },
			{ label: 'Block/ Township', value: 'shapeJson.properties.originalProperties.blockTownship.keyword' },
			{ label: 'Section/ Range', value: 'shapeJson.properties.originalProperties.rangeSection.keyword' },
			{ label: 'Abstract/ Section', value: 'shapeJson.properties.originalProperties.abstractNameShortName.keyword' },
			{ label: 'Map Status', value: 'shapeJson.properties.mapStatus.keyword' },
			{ label: 'Department', value: 'shapeJson.properties.department.keyword' },
			{ label: 'Basin', value: 'Basin' },
			{ label: 'Field', value: 'Field' },
		],
		layerKey: 'Parcel',
	},
	Agreements: {
		keys: [
			{ label: 'Agremeent Type', value: 'shapeJson.properties.agreementType.keyword' },
			{ label: 'Agremeent Subtype', value: 'shapeJson.properties.agreementSubtype.keyword' },
			{ label: 'Rights Type', value: 'shapeJson.properties.rightsType.keyword' },
			{ label: 'Agreement Status', value: 'shapeJson.properties.agreementStatus.keyword' },
			{ label: 'Grantor', value: 'shapeJson.properties.grantor.keyword' },
			{ label: 'Grantee', value: 'shapeJson.properties.grantee.keyword' },
			{ label: 'County', value: 'shapeJson.properties.originalProperties.County.keyword' },
			{ label: 'State', value: 'shapeJson.properties.originalProperties.State.keyword', orKey: 'StateAbbreviation' },
			{ label: 'Status', value: 'shapeJson.properties.agreementStatus.keyword' },
			{ label: 'Internal Company', value: 'shapeJson.properties.internalCompany.keyword' },
		],
		layerKey: 'Agreement',
	},
	'My Wells': {
		keys: [
			{ label: 'Operator', value: 'wellData.operator.keyword' },
			{ label: 'Well Type', value: 'wellData.wellType.keyword' },
			{ label: 'Well Profile', value: 'wellData.wellBoreProfile.keyword' },
			{ label: 'Well Status', value: 'wellData.wellStatus.keyword' },
			{ label: 'Basin', value: 'wellData.basin.keyword' },
			{ label: 'Field', value: 'wellData.field.keyword' },
			{ label: 'State', value: 'wellData.state.keyword' },
			{ label: 'County', value: 'wellData.county.keyword' },
			{ label: 'Survey', value: 'wellData.GrId1.keyword' },
			{ label: 'Block/Twsp', value: 'wellData.GrId2.keyword' },
			{ label: 'Sec/Range', value: 'wellData.GrId3.keyword' },
			{ label: 'Abstract/Sec', value: 'wellData.GrId4.keyword' },
			{ label: 'Lateral Length', value: 'wellData.lateralLength.keyword' },
			{ label: 'Formation', value: 'wellData.primaryFormation.keyword' },
			{ label: 'Pay Status', value: 'properties.status.keyword' },
			{ label: 'DO Status', value: 'properties.divOrderStatus.keyword' },
			{ label: 'Interest Type', value: 'propertyDescriptor.interestType.keyword' },
			{ label: 'Cost Free', value: 'propertyDescriptor.costFree.keyword' },
			{ label: 'Internal Company', value: 'properties.internalCompany.keyword' },
		],
		layerKey: 'wells',
	},
};
