export const RevenueStatementHeadCells = [
	{
		id: 'property.purchaserNumber',
		title: 'Payor Prop #',
		filterKey: ['purchaserNumber.keyword', 'name.keyword'],
		sort: true,
		type: 'autocomplete',
		esIndex: 'properties_flat',
		width: '200px',
	},
	{
		id: 'property.name',
		title: 'Property Name',
		filterKey: 'property.name.keyword',
		sort: true,
		width: '275px',
		disabled: true,
	},
	{
		id: 'property.state',
		title: 'State',
		filterKey: 'property.state.keyword',
		sort: true,
		width: '100px',
		disabled: true,
	},
	{
		id: 'property.county',
		title: 'County',
		filterKey: 'property.county.keyword',
		sort: true,
		width: '130px',
		disabled: true,
	},
	{
		id: 'date',
		title: 'Sales Date',
		filterKey: 'date',
		sort: true,
		type: 'date',
		width: '180px',
	},
	{
		id: 'product',
		title: 'Product',
		filterKey: 'product.keyword',
		sort: true,
		type: 'autocomplete',
		esIndex: 'checkdetails_flat',
		width: '130px',
	},
	{
		id: 'disbursement',
		title: 'Decimal Interest',
		filterKey: 'disbursement',
		sort: true,
		width: '150px',
	},
	{
		id: 'interestType',
		title: 'Interest Type',
		filterKey: 'interestType.keyword',
		sort: true,
		type: 'autocomplete',
		esIndex: 'checkdetails_flat',
		width: '200px',
	},
	{
		id: 'price',
		title: 'Avg Price',
		filterKey: 'price',
		sort: true,
		width: '100px',
	},
	{
		id: 'grossPropertyVolume',
		title: 'Prop Gross Volume',
		filterKey: 'grossPropertyVolume',
		sort: true,
		width: '150px',
	},
	{
		id: 'grossPropertyValue',
		title: 'Prop Gross Revenue',
		filterKey: 'grossPropertyValue',
		sort: true,
		width: '150px',
	},
	{
		id: 'grossOwnerVolume',
		title: 'Owner Volume',
		filterKey: 'grossOwnerVolume',
		sort: true,
		width: '150px',
	},
	{
		id: 'grossOwnerValue',
		title: 'Owner Gross Revenue',
		filterKey: 'grossOwnerValue',
		sort: true,
		width: '150px',
	},
	{
		id: 'ownerTax',
		title: 'Owner Tax Amt',
		filterKey: 'ownerTax',
		sort: true,
		width: '150px',
	},
	{
		id: 'taxType',
		title: 'Tax Type',
		filterKey: 'taxType.keyword',
		sort: true,
		type: 'autocomplete',
		esIndex: 'checkdetails_flat',
		width: '225px',
	},
	{
		id: 'ownerDeducts',
		title: 'Deduct Amount',
		filterKey: 'ownerDeducts',
		sort: true,
		width: '150px',
	},
	{
		id: 'deductType',
		title: 'Deduct Type',
		filterKey: 'deductType.keyword',
		sort: true,
		type: 'autocomplete',
		esIndex: 'checkdetails_flat',
		width: '225px',
	},
	{
		id: 'netOwnerValue',
		title: 'Owner Net Revenue',
		filterKey: 'netOwnerValue',
		sort: true,
		width: '150px',
	},
	{
		id: 'action',
		filterKey: 'action',
		title: '',
		type: 'action',
		width: '50px',
	},
];
