export const timeZoneOptions = [
	'(GMT+1:00) - European Central Time (ECT)',
	'(GMT+2:00) - Eastern European Time (EET)',
	'(GMT+2:00) - Egypt Standard Time (ART)',
	'(GMT+3:00) - Eastern African Time (EAT)',
	'(GMT+3:30) - Middle East Time (MET)',
	'(GMT+4:00) - Near East Time (NET)',
	'(GMT+5:00) - Pakistan Lahore Time (PLT)',
	'(GMT+5:30) - India Standard Time (IST)',
	'(GMT+6:00) - Bangladesh Standard Time (BST)',
	'(GMT+7:00) - Vietnam Standard Time (VST)',
	'(GMT+8:00) - China Taiwan Time (CTT)',
	'(GMT+9:00) - Japan Standard Time (JST)',
	'(GMT+9:30) - Australia Central Time (ACT)',
	'(GMT+10:00) - Australia Eastern Time (AET)',
	'(GMT+11:00) - Solomon Standard Time (SST)',
	'(GMT+12:00) - New Zealand Standard Time (NST)',
	'(GMT-11:00) - Midway Islands Time (MIT)',
	'(GMT-10:00) - Hawaii Standard Time (HST)',
	'(GMT-9:00) - Alaska Standard Time (AST)',
	'(GMT-8:00) - Pacific Standard Time (PST)',
	'(GMT-7:00) - Phoenix Standard Time (PNT)',
	'(GMT-7:00) - Mountain Standard Time (MST)',
	'(GMT-6:00) - Central Standard Time (CST)',
	'(GMT-5:00) - Eastern Standard Time (EST)',
	'(GMT-5:00) - Indiana Eastern Standard Time (IET)',
	'(GMT-4:00) - Puerto Rico and USVI Time (PRT)',
	'(GMT-3:30) - Canada Newfoundland Time (CNT)',
	'(GMT-3:00) - Argentina Standard Time (AGT)',
];
