export const timeZoneOptions = [
{title:'(GMT+1:00) - European Central Time (ECT)'},
{title:'(GMT+2:00) - Eastern European Time (EET)'},
{title:'(GMT+2:00) - Egypt Standard Time (ART)'},
{title:'(GMT+3:00) - Eastern African Time (EAT)'},
{title:'(GMT+3:30) - Middle East Time (MET)'},
{title:'(GMT+4:00) - Near East Time (NET)'},
{title:'(GMT+5:00) - Pakistan Lahore Time (PLT)'},
{title:'(GMT+5:30) - India Standard Time (IST)'},
{title:'(GMT+6:00) - Bangladesh Standard Time (BST)'},
{title:'(GMT+7:00) - Vietnam Standard Time (VST)'},
{title:'(GMT+8:00) - China Taiwan Time (CTT)'},
{title:'(GMT+9:00) - Japan Standard Time (JST)'},
{title:'(GMT+9:30) - Australia Central Time (ACT)'},
{title:'(GMT+10:00) - Australia Eastern Time (AET)'},
{title:'(GMT+11:00) - Solomon Standard Time (SST)'},
{title:'(GMT+12:00) - New Zealand Standard Time (NST)'},
{title:'(GMT-11:00) - Midway Islands Time (MIT)'},
{title:'(GMT-10:00) - Hawaii Standard Time (HST)'},
{title:'(GMT-9:00) - Alaska Standard Time (AST)'},
{title:'(GMT-8:00) - Pacific Standard Time (PST)'},
{title:'(GMT-7:00) - Phoenix Standard Time (PNT)'},
{title:'(GMT-7:00) - Mountain Standard Time (MST)'},
{title:'(GMT-6:00) - Central Standard Time (CST)'},
{title:'(GMT-5:00) - Eastern Standard Time (EST)'},
{title:'(GMT-5:00) - Indiana Eastern Standard Time (IET)'},
{title:'(GMT-4:00) - Puerto Rico and USVI Time (PRT)'},
{title:'(GMT-3:30) - Canada Newfoundland Time (CNT)'},
{title:'(GMT-3:00) - Argentina Standard Time (AGT)'},
];