# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_OPTIONS: --max_old_space_size=32768

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.15.0'
    displayName: 'Install Node.js'

  - task: Npm@1
    inputs:
      command: 'install'
    displayName: 'Npm Install'

  - script: |
      sed -i "s/cypress open/cypress open --env TENENT='$(TENENT)'/" ./package.json
      sed -i "s/login.cy.js'/login.cy.js' --env TENENT='$(TENENT)'/" ./package.json
    displayName: 'Replace Tenant Value'

  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@3
    displayName: 'Yarn Run CI'
    inputs:
      projectDirectory: src
      arguments: 'ci:cy-login-component'

  - script: |
      if [ "$(ls -A cypress/screenshots)" ]; then
        echo "Screenshots folder is not empty. Proceeding with the last three steps."
        echo "$(ls -A cypress/screenshots)"
        echo "##vso[task.setvariable variable=SCREENSHOTS_NOT_EMPTY]true"
      else
        echo "Screenshots folder is empty. Skipping the last three steps."
        echo "##vso[task.setvariable variable=SCREENSHOTS_NOT_EMPTY]false"
      fi
    displayName: 'Check Screenshots Folder'
    condition: succeededOrFailed()

  ## Copy the client to the staging directory
  - task: CopyFiles@2
    inputs:
      sourceFolder: "cypress"
      contents: |
        screenshots/**/*
        videos/**/*
      targetFolder: "$(Build.ArtifactStagingDirectory)"
      cleanTargetFolder: true
    displayName: 'Copy Screenshots and Videos'
    condition: eq(variables.SCREENSHOTS_NOT_EMPTY, 'true')  # Only run if the Screenshots folder is not empty

  ## Archive the files into a zip file for publishing
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: $(Build.ArtifactStagingDirectory)
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      includeRootFolder: false
    displayName: 'Archive Files'
    condition: eq(variables.SCREENSHOTS_NOT_EMPTY, 'true')  # Only run if the Screenshots folder is not empty

  ## Publish the zip file
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
    displayName: 'Publish Artifacts'
    condition: eq(variables.SCREENSHOTS_NOT_EMPTY, 'true')  # Only run if the Screenshots folder is not empty