# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: "ubuntu-latest"

variables:
  NODE_OPTIONS: --max_old_space_size=32768

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.15.0"
    displayName: "Install Node.js"

  - task: Npm@1
    inputs:
      command: "install"
    displayName: "Npm Install"

  - task: Npm@1
    displayName: 'npm custom'
    inputs:
      command: custom
      workingDir: src
      verbose: false
      customCommand: 'run ci:ci-login-component'
