import { API_TYPE } from 'utils/helper';

//Owners
export const RESET_SHAPE_OWNER = 'RESET_SHAPE_OWNER';
export const GET_SHAPE_OWNERS_AND_WELLS = API_TYPE('GET_SHAPE_OWNERS_AND_WELLS');
export const GET_SHAPE_OWNERS_AND_COUNT = API_TYPE('GET_SHAPE_OWNERS_AND_COUNT');
export const GET_MAP_FILTER_SHAPE_OWNERS_AND_COUNT = API_TYPE('GET_MAP_FILTER_SHAPE_OWNERS_AND_COUNT');
export const GET_MAP_FILTER_SHAPE_OWNERS_AND_WELLS = API_TYPE('GET_MAP_FILTER_SHAPE_OWNERS_AND_WELLS');
export const EXEC_ASYNC_EXPORT_JOB = API_TYPE('EXEC_ASYNC_EXPORT_JOB');

//Entity
export const GET_OWNER_ENTITY_DETAILS = API_TYPE('GET_OWNER_ENTITY_DETAILS');

//Contacts
export const GET_CONTACT_CAMPAIGN = API_TYPE('GET_CONTACT_CAMPAIGN');
export const CONVERT_TAX_OWNER_TO_CONTACT = API_TYPE('CONVERT_TAX_OWNER_TO_CONTACT');
export const TOGGLE_CONTACT_ACTIONS_PANEL = 'TOGGLE_CONTACT_ACTIONS_PANEL'
export const SET_ACTIVE_MODULE_CONTACT = 'SET_ACTIVE_MODULE_CONTACT'
export const CONVERT_MULTIPLE_OWNER_TO_CONTACT = API_TYPE('CONVERT_MULTIPLE_OWNER_TO_CONTACT');

//Common
export const EXEC_COMMON_ASYNC_EXPORT_JOB = API_TYPE('EXEC_COMMON_ASYNC_EXPORT_JOB');
export const TOGGLE_BULK_UPLOAD = 'TOGGLE_BULK_UPLOAD';
export const TOGGLE_QUICK_ACTIONS_PANEL = "TOGGLE_QUICK_ACTIONS_PANEL";
export const SET_ACTIVE_MODULE = "SET_ACTIVE_MODULE";
export const SET_REDUX_KEY = "SET_REDUX_KEY";

//App
export const SET_USER = 'SET_USER'
export const SET_FREEZE_LOCATION = 'SET_FREEZE_LOCATION'

//Session
export const CURRENT_USER_GRID_VIEW_SETTINGS = API_TYPE('CURRENT_USER_GRID_VIEW_SETTINGS');
export const SET_CURRENT_USER_GRID_VIEW = API_TYPE('SET_CURRENT_USER_GRID_VIEW');
export const UPDATE_USER_GRID_VIEW_SETTING = API_TYPE('UPDATE_USER_GRID_VIEW_SETTING');
export const SET_USER_GRID_VIEW_FILTERS = 'SET_USER_GRID_VIEW_FILTERS';

export const UPDATE_PIN_COMMENTS = 'UPDATE_PIN_COMMENTS';


 

