import { API_TYPE } from 'utils/helper';

//Owners
export const GET_SHAPE_OWNERS_AND_WELLS = API_TYPE('GET_SHAPE_OWNERS_AND_WELLS');
export const GET_SHAPE_OWNERS_AND_COUNT = API_TYPE('GET_SHAPE_OWNERS_AND_COUNT');
export const GET_MAP_FILTER_SHAPE_OWNERS_AND_COUNT = API_TYPE('GET_MAP_FILTER_SHAPE_OWNERS_AND_COUNT');
export const GET_MAP_FILTER_SHAPE_OWNERS_AND_WELLS = API_TYPE('GET_MAP_FILTER_SHAPE_OWNERS_AND_WELLS');

//Contacts
export const GET_CONTACT_CAMPAIGN = API_TYPE('GET_CONTACT_CAMPAIGN');
export const CONVERT_TAX_OWNER_TO_CONTACT = API_TYPE('CONVERT_TAX_OWNER_TO_CONTACT');

//Common
export const TOGGLE_BULK_UPLOAD = 'TOGGLE_BULK_UPLOAD'

//App
export const SET_USER = 'SET_USER'