// Notifications
export const SHOW_INFO_MESSAGE = 'SHOW_INFO_MESSAGE';
export const SHOW_SUCCESS_MESSAGE = 'SHOW_SUCCESS_MESSAGE';
export const SHOW_wARNING_MESSAGE = 'SHOW_wARNING_MESSAGE';
export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';

export const HIDE_INFO_MESSAGE = 'HIDE_INFO_MESSAGE';
export const HIDE_SUCCESS_MESSAGE = 'HIDE_SUCCESS_MESSAGE';
export const HIDE_wARNING_MESSAGE = 'HIDE_wARNING_MESSAGE';
export const HIDE_ERROR_MESSAGE = 'HIDE_ERROR_MESSAGE';

// ContactDetailCard
export const TOGGLE_RIGHT_COLUMN = 'TOGGLE_RIGHT_COLUMN';
export const SET_CONTACT_DETAIL_CARD_STATE = 'SET_CONTACT_DETAIL_CARD_STATE';

// AddParcelInterest
export const SET_ADD_PARCEL_INTEREST_STATE = 'SET_ADD_PARCEL_INTEREST_STATE';

// MainMap
export const SET_MAIN_MAP_STATE = 'SET_MAIN_MAP_STATE';
export const MAP_LAYERS_FILTERS_PANEL_EXPANDED = 'MAP_LAYERS_FILTERS_PANEL_EXPANDED';

// Flow
export const SET_FLOW_STATE = 'SET_FLOW_STATE';

// Land
export const SET_LAND_REDUX_KEY = 'SET_LAND_REDUX_KEY';

// Revenue
export const SET_REVENUE_KEY = 'SET_REVENUE_KEY';
export const SET_REVENUE_PROPERTIES_DATA = 'SET_REVENUE_PROPERTIES_DATA'; // For Revenue Properties Table Data

// Documents
export const SET_DOCUMENT_ID_AS_DESCRIPTOR = 'SET_DOCUMENT_ID_AS_DESCRIPTOR'; // will be used for fetching wells attached
export const WELLS_FROM_DOCUMENTS = 'WELLS_FROM_DOCUMENTS';
