import * as turf from '@turf/turf';
import hexRgb from 'hex-rgb';
import mapboxgl from 'mapbox-gl';
import _, { isEqual } from 'lodash';

import { copy, getPolygonString } from 'components/Shared/functions';
import {
	deckGlLandGridIdentifiers,
	ifDefaultLayers,
} from 'components/Shared/functions/shapeLayer';
import { popupController } from 'hookstate/popupStateController';
import { globalStateController } from 'hookstate/globalStateController';

export const random_hex_color_code = () => {
	const n = (Math.random() * 0xfffff * 1000000).toString(16);
	return `#${n.slice(0, 6)}`;
};

export const getPointSourceFromFeatures = features =>
	features.map(feature => {
		let output = feature;

		if (feature.geometry.type === 'Point') {
			output = feature;
		} else {
			output = {
				...turf.centroid(feature),
				properties: feature.properties,
			};
		}

		return output;
	});

export const getPointSourceFromGeoJson = geoJson =>
	getPointSourceFromFeatures(geoJson?.features);

export const getLayerData = (identifier, dataId, data) => {
	let layerData;

	if (ifDefaultLayers(identifier)) {
		const groupBy = (arr, property) =>
			arr.reduce((memo, x) => {
				if (!memo[x[property]]) {
					memo[x[property]] = [];
				}
				memo[x[property]].push(x);
				return memo;
			}, {});
		layerData = groupBy(data, 'layer')[dataId];
		if (!layerData) {
			layerData = [];
		}
	} else {
		layerData = data;
	}

	return layerData;
};

export const getShapeLabelProps = (shape, labelProps) => {
	const label = shape.properties?.[
		labelProps?.symbolProps?.['text-field']?.match(
			/\{(.*?)\}/
		)?.[1] || 'shapeLabel'
	] || shape.properties?.shapeLabel

	const [minX, minY, maxX, maxY] = turf.bbox(shape);

	// Calculate distances in meters using turf.distance
	const bottomLeft = [minX, minY];
	const bottomRight = [maxX, minY];
	const topLeft = [minX, maxY];

	const bboxWidth = turf.distance(bottomLeft, bottomRight, { units: 'meters' });
	const bboxHeight = turf.distance(bottomLeft, topLeft, { units: 'meters' });

	// Estimate text dimensions based on length
	const textLength = label.length;
	const maxTextWidth = bboxWidth * 0.9; // 90% of the bounding box width
	const maxTextHeight = bboxHeight * 0.9; // 90% of the bounding box height

	// Assuming a base size of 100 meters, adjust size based on the bounding box
	const baseSize = 100;
	const adjustedWidth = baseSize * (maxTextWidth / (textLength * baseSize * 0.6)); // 0.6 is an approximate width factor per character
	const adjustedHeight = baseSize * (maxTextHeight / baseSize);

	// Return the smaller of the two adjusted sizes
	const textSize = Math.min(adjustedWidth, adjustedHeight);

	return {
		...turf.centroid(shape),
		properties: {
			label: label,
			textSize
		},
	}
}

export const makeGeoJSON = (mdata, labelProps) => ({
	type: 'FeatureCollection',
	features: mdata
		.flatMap(feature => {
			if (feature.hasOwnProperty('Geometry')) {
				return {
					type: 'Feature',
					properties: feature,
					geometry: JSON.parse(feature.Geometry),
				};
			}

			if (feature.hasOwnProperty('geoJSON')) {
				return {
					type: 'Feature',
					properties: feature,
					geometry: feature.geoJSON,
				};
			}

			if (feature.latitude && feature.longitude) {
				return {
					type: 'Feature',
					properties: feature,
					geometry: {
						type: 'Point',
						coordinates: [Number(feature.longitude), Number(feature.latitude)],
					},
				};
			}

			if (feature.Latitude && feature.Longitude) {
				return {
					type: 'Feature',
					properties: feature,
					geometry: {
						type: 'Point',
						coordinates: [Number(feature.Longitude), Number(feature.Latitude)],
					},
				};
			}

			if (feature.shape) {
				const shape = JSON.parse(feature.shape);

				// This is temporary solution to replace Mapbox.Draw library's autogenerated `id`
				// with mongondb id.
				const labels = []
				if (feature._id) {
					shape.id = feature._id;
					shape.properties.id = feature._id;
					if (labelProps)
						if (shape.geometry?.type === 'MultiPolygon') {
							const shapesCoordinates = copy(shape.geometry.coordinates);
							for (let i = 0; i < shapesCoordinates.length; i++) {
								const newShape = copy(shape);
								newShape.geometry.type = 'Polygon';
								newShape.geometry.coordinates = shapesCoordinates[i];
								labels.push(getShapeLabelProps(newShape, labelProps))
							}
						} else {
							labels.push(getShapeLabelProps(shape, labelProps))
						}
				}
				return [
					shape,
					...labels,
				];
			}

			if (feature.wellData?.geoJSON?.geometries?.[0]) {
				return feature.wellData?.geoJSON?.geometries.map(geometry => ({
					type: 'Feature',
					properties: feature.wellData,
					geometry,
				}));
			}

			return feature;
		})
		.filter(feature => feature.geometry?.type),
});

export const filterUniqueFeatures = features => {
	features = features
		.map(feature => ({
			...feature,
			object: {
				...feature.object,
				id:
					feature?.object?._id ||
					feature?.object?.id ||
					feature?.object?.properties?.id ||
					feature?.object?.properties?.Id,
			},
		}))
		.filter(f => f?.object?.id);
	features = _.uniqBy(features, 'object.id');

	return features;
};

export const pickDeckObjects = ({ x, y, radius, depth }) => {
	if (!window.mapRef?.__deck) return;
	let deckFeatures = window.mapRef?.__deck?.pickMultipleObjects({
		x,
		y,
		radius,
		depth,
	});

	return filterUniqueFeatures(deckFeatures);
};

export const hexToRGB = hex => {
	// Remove the '#' symbol if present
	hex = hex.replace('#', '');

	// Expand the shorthand hexadecimal form if needed
	if (hex.length === 3) {
		hex = hex
			.split('')
			.map(char => char + char)
			.join('');
	}

	// Convert the hexadecimal to decimal values for red, green, and blue components
	const r = parseInt(hex.substring(0, 2), 16);
	const g = parseInt(hex.substring(2, 4), 16);
	const b = parseInt(hex.substring(4, 6), 16);

	// Return the RGBA string
	return `rgba(${r},${g},${b})`;
};

export const getRGBA = (rgb, a) => {
	if (!rgb) return [251, 152, 40, 255];

	if (rgb.includes('#')) rgb = hexToRGB(rgb);

	let alpha;
	if (typeof a === 'number') alpha = a;
	// else if (Array.isArray(a)) [alpha] = a.filter(val => typeof val === 'number');

	const concatIndex = rgb.indexOf('rgba') === -1 ? 4 : 5;

	let colorArray;
	if (rgb.indexOf('rgb') === -1) colorArray = hexRgb(rgb, { format: 'array', alpha });
	else
		colorArray = [
			...rgb
				.substring(concatIndex, rgb.length - 1)
				.replace(/ /g, '')
				.split(',')
				.map(s => +s),
		];

	if (colorArray[3] < 1) colorArray[3] = Math.round((colorArray[3] || 1) * 255.0);

	if (alpha) colorArray[3] = Math.round((alpha || 1) * 255.0);

	if (!colorArray[3]) colorArray[3] = 255;

	return colorArray;
};

export const divideBoundingBox = bbox => {
	const isBBoxObj = bbox.top_left && bbox.bottom_right;
	if (isBBoxObj)
		bbox = [
			bbox.top_left.lon,
			bbox.bottom_right.lat,
			bbox.bottom_right.lon,
			bbox.top_left.lat,
		];

	// Extract bbox coordinates
	const [minX, minY, maxX, maxY] = bbox;

	// Calculate center point
	const centerX = (minX + maxX) / 2;
	const centerY = (minY + maxY) / 2;

	// Create new bounding boxes
	const boxes = [
		[minX, centerY, centerX, maxY], // Top-left box
		[centerX, minY, maxX, centerY], // Bottom-right box
		[minX, minY, centerX, centerY], // Bottom-left box
		[centerX, centerY, maxX, maxY], // Top-right box
	];

	if (isBBoxObj)
		return boxes.map(bbox => ({
			top_left: {
				lat: bbox[3],
				lon: bbox[0],
			},
			bottom_right: {
				lat: bbox[1],
				lon: bbox[2],
			},
		}));

	return boxes;
};

export const dividePolygon = polygon => {
	// Calculate the centroid of the polygon
	// Calculate the bounding box (bbox) of the polygon
	const bbox = turf.bbox(polygon);
	const minX = bbox[0];
	const minY = bbox[1];
	const maxX = bbox[2];
	const maxY = bbox[3];

	// Calculate the center point of the bounding box
	const centerX = (minX + maxX) / 2;
	const centerY = (minY + maxY) / 2;

	// Create polygons for each quadrant
	const topLeft = turf.polygon([
		[
			[minX, centerY],
			[centerX, centerY],
			[centerX, maxY],
			[minX, maxY],
			[minX, centerY],
		],
	]);

	const topRight = turf.polygon([
		[
			[centerX, centerY],
			[maxX, centerY],
			[maxX, maxY],
			[centerX, maxY],
			[centerX, centerY],
		],
	]);

	const bottomLeft = turf.polygon([
		[
			[minX, minY],
			[centerX, minY],
			[centerX, centerY],
			[minX, centerY],
			[minX, minY],
		],
	]);

	const bottomRight = turf.polygon([
		[
			[centerX, minY],
			[maxX, minY],
			[maxX, centerY],
			[centerX, centerY],
			[centerX, minY],
		],
	]);

	// console.log("Quadrants:", quadrants);
	return [topLeft, topRight, bottomLeft, bottomRight];
};
export const getBeforeLayerId = (beforeLayer, layerFilters) =>
	beforeLayer?.layerPaintProps?.[0]?.id ||
	Object.values(layerFilters).find(layer => layer.layerName === beforeLayer?.identifier)
		?.id;

export const getPolygonStringFromBBox = bbox => {
	const isBBoxObj = bbox.top_left && bbox.bottom_right;
	if (isBBoxObj)
		bbox = [
			bbox.top_left.lon,
			bbox.bottom_right.lat,
			bbox.bottom_right.lon,
			bbox.top_left.lat,
		];

	const bboxPolygon = turf.bboxPolygon(bbox);

	return getPolygonString(bboxPolygon);
};

export const makeGeoJSONFromStrings = data => ({
	type: 'FeatureCollection',
	features: data.map(feature => JSON.parse(feature.geo_json)),
});

export const makeLabelGeoJsonFromStrings = data => ({
	type: 'FeatureCollection',
	features: data.map(feature => {
		const geoJSON = JSON.parse(feature.geo_json);
		if (geoJSON.geometry && geoJSON.geometry.coordinates[0].length >= 4) {
			const polygon = turf.polygon(geoJSON.geometry.coordinates);
			const centroid = turf.centroid(polygon);
			centroid.properties.AbstractName = geoJSON.properties.AbstractName;
			return centroid;
		}

		return null;
	}),
});

export const createFilterPopup = filterFeature => {
	const { geometry } = filterFeature;
	const { coordinates } = geometry;
	const popUps = document.getElementsByClassName('mapboxgl-popup');
	if (popUps[0]) {
		popUps[0].remove();
	}
	if (coordinates.length > 0) {
		const minLatitude = coordinates.reduce((a, b) => (a[0] < b[0] ? a : b))[0][0];
		const maxLongitude = coordinates.reduce((a, b) => (a[1] > b[1] ? a : b))[0][1];

		const popupCoordinate = [minLatitude, maxLongitude];

		new mapboxgl.Popup({ offset: 0, closeOnClick: false })
			.setLngLat(popupCoordinate)
			.setMaxWidth('none')
			.setHTML(`<div id="filterPopupContainer"></div>`)
			.addTo(window.mapRef);

		popupController.updateState({
			popupOpen: true,
		});

		window.setStateApp(state => ({
			...state,
			filterFeature,
		}));
	}
};

export const getAdvancedSearch = (layerGeometry, mustQuery) =>
	layerGeometry === 'Polygon'
		? [
			{
				bool: {
					must: [
						...mustQuery,
						{
							bool: {
								should: [
									{
										term: { 'properties.layerGeometry.keyword': 'Polygon' },
									},
									{
										term: { 'properties.layerGeometry.keyword': 'MultiPolygon' },
									},
								],
							},
						},
					],
				},
			},
		]
		: [
			{
				bool: {
					must: [
						...mustQuery,
						{
							bool: {
								should: [
									{
										term: { 'properties.layerGeometry.keyword': layerGeometry },
									},
								],
							},
						},
					],
				},
			},
		];
// Query made generic to support in both TransferData Manager and layerStateController
export const generateFileFilters = ({ fileLayer, pagination = { first: 10000, after: null }, extendFilters = { variables: {} } }) => {
	let mustQuery = [];
	if (fileLayer.layerShapeName) {
		mustQuery = [
			{
				term: { 'properties.layerShapeName.keyword': fileLayer.layerShapeName },
			},
		];
	}

	const advanceSearch = getAdvancedSearch(fileLayer.layerGeometry, mustQuery);

	const filters = [{ field: 'file._id.keyword', value: [fileLayer.file, fileLayer.originalFile] }];

	return {
		variables: {
			index: 'shapefile_flat',
			pagination,
			search: {
				advanceSearch,
			},
			filters,
			...extendFilters.variables
		},
	};
};

export const getGeoJsonLayerProps = (dbLayer, labelProps) => {
	const props = {};

	dbLayer.layerPaintProps?.forEach(prop => {
		switch (prop.paintType) {
			case 'fill':
				const fillColor = prop.paintProps?.['fill-color'];
				const fillOpacity = prop.paintProps?.['fill-opacity'];
				const fillStroke =
					prop.paintProps?.['fill-outline-color'] || prop.paintProps?.['line-color'];

				props.getFillColor = getRGBA(fillColor, fillOpacity);
				props.defaultColor = getRGBA(fillColor, fillOpacity);
				props.getLineColor = getRGBA(fillStroke);

				break;

			case 'circle':
				const pointColor = prop.paintProps?.['circle-color'];
				const pointOpacity = prop.paintProps?.['circle-opacity'];
				const pointStroke =
					prop.paintProps?.['circle-stroke-color'] || prop.paintProps?.['line-color'];
				const pointRadius = prop.paintProps?.['circle-radius'] || 1;
				const pointWidth = prop.paintProps?.['circle-stroke-width'] || 1;

				props.getFillColor = getRGBA(pointColor, pointOpacity);
				props.defaultColor = getRGBA(pointColor, pointOpacity);
				props.getLineColor = getRGBA(pointStroke);

				props.getPointRadius = pointRadius * 40;
				props.getLineWidth = pointWidth * 40;

				break;

			case 'line':
				const lineColor = prop.paintProps?.['line-color'];
				const lineOpaciity = prop.paintProps?.['line-opacity'];
				const lineWidth = prop.paintProps?.['line-width'] || 1;

				props.getLineWidth = lineWidth * 40;

				const getLineColor = getRGBA(lineColor, lineOpaciity);
				if (!props.getLineColor || !isEqual(getLineColor, props.getFillColor))
					props.getLineColor = getRGBA(lineColor, lineOpaciity);

				break;

			default:
				break;
		}
	});

	if (labelProps && labelProps.visibility !== 'none') {
		props.getTextSize = (f) => {
			return f.properties.textSize
		};
		props.textMaxWidth = 500;
		props.pointType = 'text';
		props.textFontFamily = 'Poppins';
		props.textSizeUnits = 'meters';
	} else if (!!labelProps?.visibility) {
		// Adhoc Fix
		props.pointType = 'icon';
	}

	return props;
};

export const getClickedFeature = ({ x, y, depth = Infinity, getLandGrid = true }) => {
	let features = pickDeckObjects({ x, y, depth });

	if (!getLandGrid) {
		features = features.filter(
			f => !deckGlLandGridIdentifiers.some(prefix => f.layer.id.startsWith(prefix))
		);
	} else {
		features = features.filter(
			f => deckGlLandGridIdentifiers.some(prefix => f.layer.id.startsWith(prefix))
		);
		return { clickedFeature: features[0], layer: { identifier: 'Land Grid' }, features };
	}

	let clickedFeature = null;
	let layer = null;

	const layers = globalStateController.getValue('layers');

	layers
		.filter(l => l.layerSettings?.showable && l.layerSettings?.visiable)
		.some(l => {
			clickedFeature = features.find(f => {
				if (l.identifier === 'Land Grid') {
					return deckGlLandGridIdentifiers.some(prefix => f.layer.id.startsWith(prefix));
				}
				return f.layer.id.startsWith(l.identifier);
			});
			if (clickedFeature) layer = l;
			return clickedFeature;
		});

	return { clickedFeature, layer, features };
};
