import filterConsts from 'components/Common/TableAddDialog/Common/filterConsts';

const tableData = [
	{
		label: 'Unit Name',
		type: 'text',
		key: 'uName',
	},
	{
		label: 'State',
		type: 'autocompletelandgrid',
		key: 'originalProperties.State',
		edit: true,
		esKey: 'State',
		newOptions: false,
		filterKey: filterConsts.state.filterKey,
		filterField: filterConsts.state.filterField,
		dependencyArray: filterConsts.state.dependencyArray,
	},
	{
		label: 'County',
		type: 'autocompletelandgrid',
		key: 'originalProperties.County',
		edit: true,
		esKey: 'County',
		newOptions: true,
		filterKey: filterConsts.county.filterKey,
		filterField: filterConsts.county.filterField,
		dependencyArray: filterConsts.county.dependencyArray,
	},
	{
		label: 'Survey',
		type: 'autocompletelandgrid',
		key: 'originalProperties.Survey',
		showStateTX: true,
		edit: true,
		esKey: 'Survey',
		filterKey: filterConsts.survey.filterKey,
		filterField: filterConsts.survey.filterField,
		dependencyArray: filterConsts.survey.dependencyArray,
	},
	{
		label: 'Block',
		type: 'autocompletelandgrid',
		key: 'originalProperties.Block',
		showStateTX: true,
		edit: true,
		esKey: 'Block',
		filterKey: filterConsts.block.filterKey,
		filterField: filterConsts.block.filterField,
		dependencyArray: filterConsts.block.dependencyArray,
	},
	{
		label: 'Section',
		type: 'autocompletelandgrid',
		key: 'originalProperties.Section',
		showStateTX: true,
		edit: true,
		esKey: 'Section',
		filterKey: filterConsts.sectiontx.filterKey,
		filterField: filterConsts.sectiontx.filterField,
		dependencyArray: filterConsts.sectiontx.dependencyArray,
	},

	{
		label: 'Abstract',
		type: 'autocompletelandgrid',
		key: 'originalProperties.AbstractName',
		showStateTX: true,
		edit: true,
		esKey: 'Abstract',
		filterKey: filterConsts.abstract.filterKey,
		filterField: filterConsts.abstract.filterField,
		dependencyArray: filterConsts.abstract.dependencyArray,
	},
	{
		label: 'Meridian',
		type: 'autocompletelandgrid',
		key: 'originalProperties.Meridian',
		showStateTX: false,
		edit: true,
		esKey: 'Meridian',
		filterKey: filterConsts.meridian.filterKey,
		filterField: filterConsts.meridian.filterField,
		dependencyArray: filterConsts.meridian.dependencyArray,
	},
	{
		label: 'Township',
		type: 'autocompletelandgrid',
		key: 'originalProperties.Township',
		showStateTX: false,
		edit: true,
		esKey: 'TownshipRange',
		filterKey: filterConsts.township.filterKey,
		filterField: filterConsts.township.filterField,
		dependencyArray: filterConsts.township.dependencyArray,
	},
	{
		label: 'Range',
		type: 'autocompletelandgrid',
		key: 'originalProperties.Range',
		showStateTX: false,
		edit: true,
		esKey: 'TownshipRange',
		filterKey: filterConsts.range.filterKey,
		filterField: filterConsts.range.filterField,
		dependencyArray: filterConsts.range.dependencyArray,
	},
	{
		label: 'Section',
		type: 'autocompletelandgrid',
		key: 'originalProperties.Section',
		showStateTX: false,
		edit: true,
		esKey: 'Section',
		filterKey: filterConsts.section.filterKey,
		filterField: filterConsts.section.filterField,
		dependencyArray: filterConsts.section.dependencyArray,
	},
	{
		label: 'Unit Number',
		type: 'text',
		key: 'uNumber',
	},
	{
		label: 'Unit Type',
		type: 'autocomplete',
		key: 'uType',
	},
	{
		label: 'Unit Status',
		type: 'autocomplete',
		options: ['Held by Production'],
		key: 'uStatus',
	},
	{
		label: 'Unit Acres',
		type: 'comma-number',
		key: 'uAcres',
	},
	{
		label: 'Calculated Acres',
		type: 'comma-number',
		key: 'shapeArea',
		nonEditable: true,
	},
	{
		label: 'Total Unit Interest',
		type: 'comma-number',
		key: 'totalUnitInterest',
		nonEditable: true,
	},
	{
		label: 'Current Operator',
		type: 'text',
		key: 'uPrimaryOperator',
	},
	{
		label: 'Field Name',
		type: 'text',
		key: 'uFieldName',
	},
	{
		label: 'Unit Depth',
		type: 'number',
		key: 'uDepth',
	},
	{
		label: 'Primary Bench',
		type: 'text',
		key: 'uPrimaryBench',
	},
	{
		label: 'Net Royalty Acres (NRA)',
		type: 'calculation',
		key: 'netRoyalityAcres',
	},
	{
		label: 'Target Pricing (per NRA)',
		type: 'currency',
		key: 'uUnitPricing',
	},

	{
		label: 'Max Pricing (per NRA)',
		type: 'currency',
		key: 'uMaxUnitPricing',
	},
	{
		label: 'Qualifier',
		type: 'custom',
		key: 'qualifier',
	},
	{
		label: 'Reviewer',
		type: 'custom',
		key: 'reviewer',
	},
	{
		label: 'Campaigns',
		type: 'custom',
		key: 'campaigns',
	},
	{
		label: 'Owner',
		type: 'ownerName',
		key: 'ownerName',
	},
];
export default tableData;
