import filterConsts from "components/Table/TableAddDialog/Common/filterConsts";

const tableData = [
  {
    label: "Unit Name",
    type: "text",
    key: "uName",
  },
  {
    label: "State",
    type: "autocompletelandgrid",
    key: "originalProperties.State",
    edit: true,
    esKey: 'State',
    newOptions: false,
    filterKey: filterConsts.state.filterKey,
    filterField: filterConsts.state.filterField,
    dependencyArray: filterConsts.state.dependencyArray,
  },
  {
    label: "County",
    type: "autocompletelandgrid",
    key: "originalProperties.County",
    edit: true,
    esKey: 'County',
    newOptions: true,
    filterKey: filterConsts.county.filterKey,
    filterField: filterConsts.county.filterField,
    dependencyArray: filterConsts.county.dependencyArray,
  },
  {
    label: "Township",
    type: "autocompletelandgrid",
    key: "originalProperties.Township",
    showStateTX: false,
    edit: true,
    esKey: 'TownshipRange',
    filterKey: filterConsts.township.filterKey,
    filterField: filterConsts.township.filterField,
    dependencyArray: filterConsts.township.dependencyArray,
  },
  {
    label: "Range",
    type: "autocompletelandgrid",
    key: "originalProperties.Range",
    showStateTX: false,
    edit: true,
    esKey: 'TownshipRange',
    filterKey: filterConsts.range.filterKey,
    filterField: filterConsts.range.filterField,
    dependencyArray: filterConsts.range.dependencyArray,
  },
  {
    label: "Section",
    type: "autocompletelandgrid",
    key: "originalProperties.Section",
    showStateTX: false,
    edit: true,
    esKey: 'Section',
    filterKey: filterConsts.section.filterKey,
    filterField: filterConsts.section.filterField,
    dependencyArray: filterConsts.section.dependencyArray,
  },
  {
    label: "Unit Number",
    type: "text",
    key: "uNumber",
  },
  {
    label: "Unit Type",
    type: "autocomplete",
    key: "uType",
  },
  {
    label: "Unit Status",
    type: "autocomplete",
    options: ["Held by Production"],
    key: "uStatus",
  },
  {
    label: "Unit Acres",
    type: "comma-number",
    key: "uAcres",
  },
  {
    label: "Calculated Acres",
    type: "comma-number",
    key: "shapeArea",
    nonEditable: true,
  },
  {
    label: "Total Unit Interest",
    type: "comma-number",
    key: "totalUnitInterest",
    nonEditable: true,
  },
  {
    label: "Current Operator",
    type: "text",
    key: "uPrimaryOperator",
  },
  {
    label: "Field Name",
    type: "text",
    key: "uFieldName",
  },
  {
    label: "Unit Depth",
    type: "number",
    key: "uDepth",
  },
  {
    label: "Primary Bench",
    type: "text",
    key: "uPrimaryBench",
  },
  {
    label: "Net Royalty Acres (NRA)",
    type: "calculation",
    key: "netRoyalityAcres",
  },
  {
    label: "Target Pricing (per NRA)",
    type: "currency",
    key: "uUnitPricing",
  },

  {
    label: "Max Pricing (per NRA)",
    type: "currency",
    key: "uMaxUnitPricing",
  },
  {
    label: "Qualifier",
    type: "custom",
    key: "qualifier",
  },
  {
    label: "Reviewer",
    type: "custom",
    key: "reviewer",
  },
  {
    label: "Campaign Name",
    type: "custom",
    key: "campaignName",
  },
];
export default tableData;
