import React, { useState, createContext } from 'react'

const NavigationContext = createContext([{}, () => {}])

const NavigationContextProvider = props => {
  const [stateNav, setStateNav] = useState({
    selectedMenuIndexFind: 0,
    selectedMenuIndexTrack: 0,
    selectedMenuIndexTransact: 0,
    selectedMenuIndexTitle: 0,
    selectedMenuIndexAlerts: 0,    
    filterWellProfile:null,
    filterWellType:null,
    filterWellStatus:null,
    filterOperator:null,
    filterInterest:null,
    filterOwnerType:null,
    filterCumulativeOil:null,
    filterCumulativeGas:null,
    filterCumulativeWater:null,
    filterFirstMonthWater:null,
    filterFirstThreeMonthWater:null,
    filterFirstSixMonthWater:null,
    filterFirstTwelveMonthWater:null,
    filterLastMonthWater:null,
    filterLastSixMonthWater:null,
    filterLastTwelveMonthWater:null,
    filterFirstMonthGas:null,
    filterFirstThreeMonthGas:null,
    filterFirstSixMonthGas:null,
    filterFirstTwelveMonthGas:null,
    filterLastMonthGas:null,
    filterLastSixMonthGas:null,
    filterLastTwelveMonthGas:null,
    filterFirstMonthOil:null,
    filterFirstSixMonthOil:null,
    filterFirstTwelveMonthOil:null,
    filterLastMonthOil:null,
    filterLastSixMonthOil:null,
    filterLastTwelveMonthOil:null,
    filterOwnershipTypeReligiousInstitutions:null,
    filterOwnershipTypeGovernmentalBodies:null,
    filterOwnershipTypeNonProfits:null,
    filterOwnershipTypeTrusts:null,
    filterOwnershipTypeCorporations:null,
    filterOwnershipTypeEducationalInstitutions:null,
    filterOwnershipTypeIndividuals:null,
    filterOwnershipTypeUnknown:null,
    filterInterestTypeRoyaltyInterest:null,
    filterInterestTypeOverrideRoyalty:null,
    filterInterestTypeWorkingInterest:null,
    filterInterestTypeProductionPayment:null,
    filterGeography: null,
    filterGeographyState: null,
    filterGeographyCounty: null,
    filterGeographySurvey : null,
    filterGeographyAbstract: null,
    searchInputValue:null,
    statusName:[],
    typeName:[],
    profileName:[],
    interestName:[],
    ownerTypeName:[],
    dateTypeName: [],
    prodTypeName: [],
    countyName: null,
    stateName: null,
    displayStateName: null,
    surveyName: null, 
    abstractName: null,
    operatorName:null,
    wellFilterCount:0,
    ownershipFilterCount:0,
    productionFilterCount:0,
    geographyFilterCount: 0,
    operators: null,
    filterPermitDateRange: null,
    filterSpudDateRange: null,
    filterCompletetionDateRange: null,
    filterFirstProdDateRange: null,
    permitDateFrom: null,
    permitDateTo: null,
    spudDateFrom: null,
    spudDateTo: null,
    completetionDateFrom: null,
    completetionDateTo: null,
    firstProdDateFrom: null,
    firstProdDateTo: null,
    displayFilters: null,
    statesInFilter: null,
    countiesInFilter: null,
    surveysInFilter: null,
    asbtractsInFilter: null,
  })
  return (
    <NavigationContext.Provider value={[stateNav, setStateNav]}>
      {props.children}
    </NavigationContext.Provider>
  )
}

export { NavigationContext, NavigationContextProvider }
