export const FEATURES = {
    USER_MANAGEMENT: 'User Management',
    MEPLER: 'MEPLER',
    IDICORE: 'idiCORE',
    MAPSHAPEEXPORT: 'mapShapeExport',
    LANDMODULE: 'landModule',
    REVENUEMODULE: 'revenueModule',
    LANDPORTFOLIO: 'landPortfolio',
    LANDREPORTINGGROUPS: 'landReportingGroups',
    CONTACTSUBMENU: 'ContactsSubMenu',
    CALENDAR_OBLIGATIONS: 'CALENDAR_OBLIGATIONS',
    CALENDAR_EXPIRATIONS: 'CALENDAR_EXPIRATIONS',
    LANDGRIDSEARCH: 'landGridSearch',
    TRACTIMPORT: 'tractImport',
    UNITIMPORT: 'unitImport',
    SHAPEELASTIC: 'ShapeFileImport',
    USERSNAP: "userSnap",
    CONTACTGRIDEXPORT: 'ContactGridExport',
    EDITABLE_WORKSPACE: 'editableWorkspaceName',
    SHOWUSERPRIVILEGES: 'showUserPrivileges',
    AGREEMENT_LAYER: 'AgreementLayer',
    ANALYTICS: 'analyticsModule',
    RECENTPERMITLAYER:'showRecentPermitsLayer',
    TRACKEDWELLSLAYER:'showTrackedWellsLayer',
    USERTAGSLAYER:'showUserTagsLayer',
}