export const campaignVariables = {
    esIndex: "contacts_flat",
    filterKey: "campaignName.keyword",
    search: '',
    size: 50,
  }

export const wellsKeys = [
  "wellName",
  "wellNumber",
  "api",
  "wellType",
  "wellStatus",
  "operator",
  "county",
  "state",
  "wellBoreProfile",
  "latitude",
  "longitude",
  "geoJSON",
  "permitApprovedDate",
  "spudDate",
  "daysSinceDrilled",
  "completionDate",
  "daysSinceCompletion",
  "firstProductionDate",
  "measuredDepth",
  "basin",
  "play",
  "primaryFormation",
  "field",
  "permitNumber",
  "leaseId",
  "leaseName",
  "hasLine",
  "isPermit",
  "cumulativeOil",
  "cumulativeGas",
  "boeTotal",
  "cumulativeWater",
  "ipOil",
  "ipGas",
  "firstThreeMonthOil",
  "firstThreeMonthGas",
  "firstThreeMonthWater",
  "firstSixMonthOil",
  "firstSixMonthGas",
  "firstSixMonthWater",
  "firstTwelveMonthOil",
  "firstTwelveMonthGas",
  "firstTwelveMonthWater",
  "lastSixMonthOil",
  "lastSixMonthGas",
  "lastSixMonthWater",
  "lastTwelveMonthOil",
  "lastTwelveMonthGas",
  "lastTwelveMonthBOE",
  "lastTwelveMonthWater",
  "lastMonthOil",
  "lastMonthGas",
  "lastMonthWater",
  "firstMonthOil",
  "firstMonthGas",
  "firstMonthWater",
  "ipWater",
  "ownershipTypeCorporations",
  "ownershipTypeEducationalInstitutions",
  "ownershipTypeGovernmentalBodies",
  "ownershipTypeIndividuals",
  "ownershipTypeNonProfits",
  "ownershipTypeReligiousInstitutions",
  "ownershipTypeTrusts",
  "ownershipTypeUnknown",
  "interestTypeRoyaltyInterest",
  "interestTypeOverrideRoyalty",
  "interestTypeWorkingInterest",
  "interestTypeProductionPayment",
  "hasOwner",
  "ownerAppraisalLess1k",
  "ownerAppraisal1to10k",
  "ownerAppraisal10to25k",
  "ownerAppraisalOver25k",
  "sysStartTime",
  "sort",
  "Id",
  "CurrentOperator",
  "Lease",
  "MaxCompletionRecordDate",
  "plugDate"
]

export const contactManagementRoutes = {
  ALLENTITIES: {
    featureFlag: "CONTACTSUBMENU",
    title: "All Entities",
    link: "/contacts",
    component: "ContactsTable",
  },
  LEADS: {
    featureFlag: "CONTACTSUBMENU",
    title: "Leads",
    link: "/contacts/leads",
    component: "ContactsTable",
    filterValue: 'Lead',
    showAnalytics: true,
  },
  PROSPECTS: {
    featureFlag: "CONTACTSUBMENU",
    title: "Prospects",
    link: "/contacts/prospects",
    component: "ContactsTable",
    filterValue: 'Prospect',
    showAnalytics: true,
  },
  CONTACTS: {
    featureFlag: "CONTACTSUBMENU",
    title: "Contacts",
    link: "/contacts/contact",
    component: "ContactsTable",
    filterValue: 'Contact',
    showAnalytics: true,
  },
  ACTIVITY: {
    featureFlag: "CONTACTSUBMENU",
    title: "Activity Dashboard",
    link: "/contacts/activityDashboard",
    component: "ContactsTable",
  },
  CAMPAIGN: {
    featureFlag: "CONTACTSUBMENU",
    title: "Campaign Management",
    link: "/contacts/campaignManagement",
    component: "ContactsTable",
  },
};

export const contactsAnalyticsCards = [
  {
    heading: "Total Contacts",
    points: 0,
  },
  {
    heading: "Recently Added",
    points: 0,
  },
  {
    heading: "Recently Contacted",
    points: 0,
  },
  {
    heading: "Missing Contact Info",
    points: 0,
    type: "warning",
  },
];