export const campaignVariables = {
  esIndex: "contacts_flat",
  filterKey: "campaignName.keyword",
  search: "",
  size: 50,
};

export const wellsKeys = [
  "wellName",
  "wellNumber",
  "api",
  "wellType",
  "wellStatus",
  "operator",
  "county",
  "state",
  "wellBoreProfile",
  "latitude",
  "longitude",
  "geoJSON",
  "permitApprovedDate",
  "spudDate",
  "daysSinceDrilled",
  "completionDate",
  "daysSinceCompletion",
  "firstProductionDate",
  "measuredDepth",
  "basin",
  "play",
  "primaryFormation",
  "field",
  "permitNumber",
  "leaseId",
  "leaseName",
  "hasLine",
  "isPermit",
  "cumulativeOil",
  "cumulativeGas",
  "boeTotal",
  "cumulativeWater",
  "ipOil",
  "ipGas",
  "firstThreeMonthOil",
  "firstThreeMonthGas",
  "firstThreeMonthWater",
  "firstSixMonthOil",
  "firstSixMonthGas",
  "firstSixMonthWater",
  "firstTwelveMonthOil",
  "firstTwelveMonthGas",
  "firstTwelveMonthWater",
  "lastSixMonthOil",
  "lastSixMonthGas",
  "lastSixMonthWater",
  "lastTwelveMonthOil",
  "lastTwelveMonthGas",
  "lastTwelveMonthBOE",
  "lastTwelveMonthWater",
  "lastMonthOil",
  "lastMonthGas",
  "lastMonthWater",
  "firstMonthOil",
  "firstMonthGas",
  "firstMonthWater",
  "ipWater",
  "ownershipTypeCorporations",
  "ownershipTypeEducationalInstitutions",
  "ownershipTypeGovernmentalBodies",
  "ownershipTypeIndividuals",
  "ownershipTypeNonProfits",
  "ownershipTypeReligiousInstitutions",
  "ownershipTypeTrusts",
  "ownershipTypeUnknown",
  "interestTypeRoyaltyInterest",
  "interestTypeOverrideRoyalty",
  "interestTypeWorkingInterest",
  "interestTypeProductionPayment",
  "hasOwner",
  "ownerAppraisalLess1k",
  "ownerAppraisal1to10k",
  "ownerAppraisal10to25k",
  "ownerAppraisalOver25k",
  "sysStartTime",
  "sort",
  "Id",
  "CurrentOperator",
  "Lease",
  "MaxCompletionRecordDate",
  "plugDate",
];

export const contactManagementRoutes = {
  ALLENTITIES: {
    featureFlag: "CONTACTSUBMENU",
    title: "All Entities",
    link: "/contacts",
    linkPrefix: "/contacts",
    component: "ContactsTable",
    value: "All",
    search: true,
    isDefault: true,
  },
  LEADS: {
    featureFlag: "CONTACTSUBMENU",
    title: "Leads",
    link: "/contacts/leads",
    linkPrefix: "/contacts/leads",
    component: "ContactsTable",
    filterValue: "Lead",
    showAnalytics: true,
    value: "Leads",
    search: true,
    isDefault: true,
  },
  PROSPECTS: {
    featureFlag: "CONTACTSUBMENU",
    title: "Prospects",
    link: "/contacts/prospects",
    linkPrefix: "/contacts/prospects",
    component: "ContactsTable",
    filterValue: "Prospect",
    showAnalytics: true,
    value: "Prospects",
    search: true,
    isDefault: true,
  },
  CONTACTS: {
    featureFlag: "CONTACTSUBMENU",
    title: "Contacts",
    link: "/contacts/contact",
    linkPrefix: "/contacts/contact",
    component: "ContactsTable",
    filterValue: "Contact",
    showAnalytics: true,
    value: "Contacts",
    search: true,
    isDefault: true,
  },
  ACTIVITY: {
    featureFlag: "CONTACTSUBMENU",
    title: "Activity Dashboard",
    link: "/contacts/activityDashboard",
    linkPrefix: "/contacts/activityDashboard",
    component: "ActivitiesDashboard",
    value: "Activities",
    search: false,
    isDefault: true,
  },
  CAMPAIGNS: {
    featureFlag: "CONTACTSUBMENU",
    title: "Campaigns",
    link: "/contacts/campaigns",
    linkPrefix: "/contacts/campaigns",
    component: "CampaignManagement",
    value: "Campaigns",
    search: true,
    isDefault: true,
  },
  CAMPAIGN_DETAIL: {
    featureFlag: "CONTACTSUBMENU",
    title: "Campaigns",
    link: "/contacts/campaign/details/:campaignId",
    linkPrefix: "/contacts/campaign/details",
    component: "CampaignDetail",
    value: "Campaigns",
    search: true,
    isDefault: true,
    isExcluded: true,
    parent: "CAMPAIGNS",
  },
};

export const analyticsManagementRoutes = {
  ACTIVITY: {
    featureFlag: "CONTACTSUBMENU",
    title: "CRM",
    link: "/analytics",
    component: "ActivitiesDashboard",
    value: "CRM",
    search: true,
    isDefault: true,
  },
  LEADS: {
    featureFlag: "CONTACTSUBMENU",
    title: "Land",
    link: "/analytics/land",
    component: "Land",
    value: "Land",
    search: false,
    isDefault: false,
  },
  PROSPECTS: {
    featureFlag: "CONTACTSUBMENU",
    title: "Revenue",
    link: "/analytics/revenue",
    component: "Revenue",
    filterValue: "Prospect",
    showAnalytics: true,
    value: "Revenue",
    search: false,
    isDefault: false,
  },
};

export const contactsAnalyticsCards = [
  {
    heading: "Total Contacts",
    points: 0,
  },
  {
    heading: "Recently Added",
    points: 0,
  },
  {
    heading: "Recently Contacted",
    points: 0,
  },
  {
    heading: "Missing Contact Info",
    points: 0,
    type: "warning",
  },
];

export const activityTypes = [
  {
    value: "deadline",
    label: "Deadlines",
  },
  {
    value: "call",
    label: "Calls",
  },
  {
    value: "text_message",
    label: "Text Messages",
  },
  {
    value: "email",
    label: "Emails",
  },
  {
    value: "meeting",
    label: "Meetings",
  },
  {
    value: "task",
    label: "Tasks",
  },
  {
    value: "mailer",
    label: "Mailers",
  },
];

export const CUSTOM_DATES = {
  ALL_DATES: "All Dates",
  THIS_YEAR_TO_LAST_MONTH: "This year to last month",
  THIS_YEAR_TO_DATE: "This year to date",
  LAST_YEAR_TO_DATE: "Last year to date",
  LAST_MONTH: "Last Month",
  THIS_MONTH: "This Month",
  LAST_QUARTER: "Last Quarter",
  THIS_QUARTER: "This Quarter",
  THIS_WEEK: "This Week",
  LAST_WEEK: "Last Week",
  LAST_YEAR: "Last Year",
  CUSTOM: "Custom",
};

export const tractFilterColumnsHeader = [
  {
    label: "Department",
    filterKey: "shapeJson.properties.department.keyword",
    name: "department"
  },
  {
    label: "State",
    filterKey: 'shapeJson.properties.originalProperties.State.keyword',

    name: "state"
  },
  {
    label: "County",
    filterKey: "shapeJson.properties.originalProperties.County.keyword",
    name: "County"
  },
  {
    label: "Owner Name",
    filterKey: "shapeJson.properties.department.keyword",
    name: "department",
    disabled: true
  }]

export const wellsFilterColumnsHeader = [
  // Ali - Commenting this as we don't have this existing functionality
  // {
  //   label: "Classification",
  //   filterKey: 'wellData.classification.keyword',
  //   name: "classification"
  // },
  {
    label: "Internal Company",
    filterKey: 'properties.internalCompany.keyword',
    name: "internalCompany"
  },
  {
    label: "Pay Status",
    filterKey: 'properties.status.keyword',
    name: "payStatus"
  }
]

export const tractInterestFilterColumnsHeader = [
  {
    label: "Department",
    filterKey: "shape.shapeJson.properties.department.keyword",
    name: "department",

  },
  {
    label: "State",
    filterKey: ["shape.shapeJson.properties.originalProperties.State.keyword",
      "shape.shapeJson.properties.originalProperties.StateAbbreviation.keyword"],
    name: "State"
  },
  {
    label: "County",
    filterKey: "shape.shapeJson.properties.originalProperties.County.keyword",
    name: "County"
  },
  {
    label: "Owner Name",
    filterKey: "contact.entityDetail.name.keyword",
    name: "name"
  }
]
export const US_STATES = {
  "Alabama": "AL",
  "Alaska": "AK",
  "American Samoa": "AS",
  "Arizona": "AZ",
  "Arkansas": "AR",
  "California": "CA",
  "Colorado": "CO",
  "Connecticut": "CT",
  "Delaware": "DE",
  "District of Columbia": "DC",
  "Federated States Of Micronesia": "FM",
  "Florida": "FL",
  "Georgia": "GA",
  "Guam": "GU",
  "Hawaii": "HI",
  "Idaho": "ID",
  "Illinois": "IL",
  "Indiana": "IN",
  "Iowa": "IA",
  "Kansas": "KS",
  "Kentucky": "KY",
  "Louisiana": "LA",
  "Maine": "ME",
  "Marshall Islands": "MH",
  "Maryland": "MD",
  "Massachusetts": "MA",
  "Michigan": "MI",
  "Minnesota": "MN",
  "Mississippi": "MS",
  "Missouri": "MO",
  "Montana": "MT",
  "Nebraska": "NE",
  "Nevada": "NV",
  "New Hampshire": "NH",
  "New Jersey": "NJ",
  "New Mexico": "NM",
  "New York": "NY",
  "North Carolina": "NC",
  "North Dakota": "ND",
  "Northern Mariana Islands": "MP",
  "Ohio": "OH",
  "Oklahoma": "OK",
  "Oregon": "OR",
  "Palau": "PW",
  "Pennsylvania": "PA",
  "Puerto Rico": "PR",
  "Rhode Island": "RI",
  "South Carolina": "SC",
  "South Dakota": "SD",
  "Tennessee": "TN",
  "Texas": "TX",
  "Utah": "UT",
  "Vermont": "VT",
  "Virgin Islands": "VI",
  "Virginia": "VA",
  "Washington": "WA",
  "West Virginia": "WV",
  "Wisconsin": "WI",
  "Wyoming": "WY"
}

export const US_STATES_CODES = {
  "AL": "Alabama",
  "AK": "Alaska",
  "AS": "American Samoa",
  "AZ": "Arizona",
  "AR": "Arkansas",
  "CA": "California",
  "CO": "Colorado",
  "CT": "Connecticut",
  "DE": "Delaware",
  "DC": "District of Columbia",
  "FM": "Federated States Of Micronesia",
  "FL": "Florida",
  "GA": "Georgia",
  "GU": "Guam",
  "HI": "Hawaii",
  "ID": "Idaho",
  "IL": "Illinois",
  "IN": "Indiana",
  "IA": "Iowa",
  "KS": "Kansas",
  "KY": "Kentucky",
  "LA": "Louisiana",
  "ME": "Maine",
  "MH": "Marshall Islands",
  "MD": "Maryland",
  "MA": "Massachusetts",
  "MI": "Michigan",
  "MN": "Minnesota",
  "MS": "Mississippi",
  "MO": "Missouri",
  "MT": "Montana",
  "NE": "Nebraska",
  "NV": "Nevada",
  "NH": "New Hampshire",
  "NJ": "New Jersey",
  "NM": "New Mexico",
  "NY": "New York",
  "NC": "North Carolina",
  "ND": "North Dakota",
  "MP": "Northern Mariana Islands",
  "OH": "Ohio",
  "OK": "Oklahoma",
  "OR": "Oregon",
  "PW": "Palau",
  "PA": "Pennsylvania",
  "PR": "Puerto Rico",
  "RI": "Rhode Island",
  "SC": "South Carolina",
  "SD": "South Dakota",
  "TN": "Tennessee",
  "TX": "Texas",
  "UT": "Utah",
  "VT": "Vermont",
  "VI": "Virgin Islands",
  "VA": "Virginia",
  "WA": "Washington",
  "WV": "West Virginia",
  "WI": "Wisconsin",
  "WY": "Wyoming"
}

export const AdminManagementRoutes = {
  CUSTOMIZATIONS: {
    featureFlag: "CONTACTSUBMENU",
    title: "Customization",
    link: "/admin",
    component: "Admin",
    value: "Activities",
    search: true,
    isDefault: true,
  },
  FLOWLINESETTING: {
    featureFlag: "CONTACTSUBMENU",
    title: "Flow Settings",
    link: "/admin/fowSetting",
    component: "Admin",
    value: "Activities",
    search: false,
    isDefault: true,
  },
  MEMBERACCESS: {
    featureFlag: "CONTACTSUBMENU",
    title: "Member Access",
    link: "/admin/memberAccess",
    component: "Admin",
    filterValue: "Prospect",
    showAnalytics: true,
    value: "Prospects",
    search: false,
    isDefault: true,
  },
  TERMS: {
    featureFlag: "CONTACTSUBMENU",
    title: "Terms",
    link: "/admin/terms",
    component: "Admin",
    filterValue: "Prospect",
    showAnalytics: true,
    value: "Prospects",
    search: false,
    isDefault: true,
  },
  ORGANIZATIONSETTING: {
    featureFlag: "CONTACTSUBMENU",
    title: "Organization Settings",
    link: "/admin/organizationSettings",
    component: "Admin",
    filterValue: "Prospect",
    showAnalytics: true,
    value: "Prospects",
    search: false,
    isDefault: true,
  },
  TEAMINSIGHTS: {
    featureFlag: "CONTACTSUBMENU",
    title: "Team Insights",
    link: "/admin/teamInsight",
    component: "Admin",
    filterValue: "Prospect",
    showAnalytics: true,
    value: "Prospects",
    search: false,
    isDefault: true,
  },
  BILLING: {
    featureFlag: "CONTACTSUBMENU",
    title: "Billing",
    link: "/admin/billing",
    component: "Admin",
    filterValue: "Prospect",
    showAnalytics: true,
    value: "Prospects",
    search: false,
    isDefault: true,
  },
};
