import NavigationFlagField from 'components/MRTTable/Common/TableCells/NavigationFlagField';

export const CommonSchema = {
	COMMENTS: {
		name: 'comments',
		accessorKey: 'comments',
		header: '',
		size: 120,
		isPinned: false,
		hidden: false,
		filter: false,
		isSearchField: false,
		enableSorting: false,
		type: 'string',
		enableColumnActions: false,
		enableHiding: false,
		enableColumnFilter: false,
		enableColumnOrdering: false,
		enableResizing: false,
	},
	TAGS: {
		name: 'tags.tag.keyword',
		accessorKey: 'tags.tag',
		header: 'Tags',
		size: 250,
		isPinned: false,
		hidden: false,
		filter: true,
		isSearchField: true,
		enableSorting: true,
		type: 'string',
		enableColumnFilter: false,
		enableColumnActions: false,
		enableColumnOrdering: false,
		enableResizing: false,
	},
	HIDDEN: {
		header: ' ',
		isSearchField: false,
		hidden: true,
		enablePinning: false,
		enableHiding: false,
		enableColumnActions: false,
		enableColumnOrdering: false,
		enableSorting: false,
	},
	INITAIL_PINNED: {
		isPinned: true,
		enableHiding: false,
		filter: true,
		type: 'string',
		isExternalFilter: false,
		enableColumnActions: true,
		enableColumnOrdering: false,
		size: 350,
	},
	STRING_COLUMN: {
		size: 250,
		isPinned: false,
		hidden: false,
		filter: true,
		isSearchField: true,
		enableSorting: true,
		type: 'string',
		filterVariant: 'select',
	},
	NUMBER_COLUMN: {
		size: 250,
		isPinned: false,
		hidden: false,
		filter: true,
		isSearchField: true,
		enableSorting: true,
		type: 'number',
	},
	ACTION_COLUMN: {
		header: ' ',
		isPinned: false,
		hidden: false,
		filter: true,
		isSearchField: false,
		enableSorting: true,
		enableColumnActions: false,
		enableHiding: false,
		type: 'string',
		enableColumnFilter: false,
		enableColumnOrdering: false,
		enableResizing: false,
	},
	NAVIGATION_CHECK_COLUMN: featureName => {
		const column = {
			isPinned: false,
			hidden: false,
			filter: false,
			isSearchField: false,
			enableSorting: false,
			enableColumnActions: false,
			enableHiding: false,
			type: 'string',
			enableColumnFilter: false,
			enableColumnOrdering: true,
			enableResizing: true,
			Cell: ({ row }) => {
				return <NavigationFlagField featureName={featureName} row={row?.original} />;
			},
		};
		return column;
	},
};
