import filterConsts from "components/Table/TableAddDialog/Common/filterConsts";

const tableData = [
    {
        label: "Tract Name",
        type: "text",
        key: "shapeLabel",
        nonEditable: false,
    },
    {
        label: "State",
        type: "autocompletelandgrid",
        key: "originalProperties.State",
        edit: true,
        mongoKey: 'state',
        filterKey: filterConsts.state.filterKey,
        filterField: filterConsts.state.filterField,
        dependencyArray: filterConsts.state.dependencyArray,
    },
    {
        label: "Country",
        type: "autocompletelandgrid",
        key: "originalProperties.County",
        edit: true,
        mongoKey: 'county',
        filterKey: filterConsts.county.filterKey,
        filterField: filterConsts.county.filterField,
        dependencyArray: filterConsts.county.dependencyArray,
    },
    {
        label: "Survey",
        type: "autocompletelandgrid",
        key: "originalProperties.Survey",
        showStateTX: true,
        edit: true,
        mongoKey: 'survey',
        filterKey: filterConsts.survey.filterKey,
        filterField: filterConsts.survey.filterField,
        dependencyArray: filterConsts.survey.dependencyArray,
    },
    {
        label: "Block",
        type: "autocompletelandgrid",
        key: "originalProperties.Block",
        showStateTX: true,
        edit: true,
        mongoKey: 'block',
        filterKey: filterConsts.block.filterKey,
        filterField: filterConsts.block.filterField,
        dependencyArray: filterConsts.block.dependencyArray,
    },
    {
        label: "Section",
        type: "autocompletelandgrid",
        key: "originalProperties.Section",
        showStateTX: true,
        edit: true,
        mongoKey: 'section',
        filterKey: filterConsts.sectiontx.filterKey,
        filterField: filterConsts.sectiontx.filterField,
        dependencyArray: filterConsts.sectiontx.dependencyArray,
    },
    {
        label: "Abstract",
        type: "autocompletelandgrid",
        key: "originalProperties.AbstractName",
        showStateTX: true,
        edit: true,
        mongoKey: 'abstract',
        filterKey: filterConsts.abstract.filterKey,
        filterField: filterConsts.abstract.filterField,
        dependencyArray: filterConsts.abstract.dependencyArray,
    },
    {
        label: "Alt Survey",
        type: "autocomplete",
        // type: "autocompletelandgrid",
        key: "originalProperties.Grantee",
        showStateTX: true,
        edit: true,
        // mongoKey: 'altSurvey',
        // filterKey: filterConsts.altSurvey.filterKey,
        // filterField: filterConsts.altSurvey.filterField,
        // dependencyArray: filterConsts.altSurvey.dependencyArray,
    },
    {
        label: "Meridian",
        type: "autocompletelandgrid",
        key: "originalProperties.Meridian",
        showStateTX: false,
        edit: true,
        mongoKey: 'meridian',
        filterKey: filterConsts.meridian.filterKey,
        filterField: filterConsts.meridian.filterField,
        dependencyArray: filterConsts.meridian.dependencyArray,
    },
    {
        label: "Township",
        type: "autocompletelandgrid",
        key: "originalProperties.Township",
        showStateTX: false,
        edit: true,
        mongoKey: 'township',
        filterKey: filterConsts.township.filterKey,
        filterField: filterConsts.township.filterField,
        dependencyArray: filterConsts.township.dependencyArray,
    },
    {
        label: "Range",
        type: "autocompletelandgrid",
        key: "originalProperties.Range",
        showStateTX: false,
        edit: true,
        mongoKey: 'range',
        filterKey: filterConsts.range.filterKey,
        filterField: filterConsts.range.filterField,
        dependencyArray: filterConsts.range.dependencyArray,
    },
    {
        label: "Section",
        type: "autocompletelandgrid",
        key: "originalProperties.Section",
        showStateTX: false,
        edit: true,
        mongoKey: 'section',
        filterKey: filterConsts.section.filterKey,
        filterField: filterConsts.section.filterField,
        dependencyArray: filterConsts.section.dependencyArray,
    },
    {
        label: "Gross Acres",
        type: "comma-number",
        key: "sdGrossAcres",
        nonEditable: false,
    },
    {
        label: "Calculated Acres",
        type: "comma-number",
        key: "shapeArea",
        nonEditable: true,
    },
    // {
    //     label: "Tract Status",
    //     type: "autocompletelandgrid",
    //     key: "tractStatus",
    //     edit: true,
    // },
    {
        label: "Department",
        type: "autocomplete",
        // type: "autocompletelandgrid",
        key: "department",
        nonEditable: false,
        // mongoKey: 'department',
        // filterKey: filterConsts.department.filterKey,
        // filterField: filterConsts.department.filterField,
        // dependencyArray: filterConsts.department.dependencyArray,
    },
    {
        label: "Map Status",
        type: "autocomplete",
        // type: "autocompletelandgrid",
        key: "mapStatus",
        edit: true,
        // mongoKey: 'mapStatus',
        // filterKey: filterConsts.mapStatus.filterKey,
        // filterField: filterConsts.mapStatus.filterField,
        // dependencyArray: filterConsts.mapStatus.dependencyArray,
    },
    {
        label: "Basin",
        type: "autocomplete",
        key: "basin",
        edit: true,
        // mongoKey: 'basin',
        // filterKey: filterConsts.basin.filterKey,
        // filterField: filterConsts.basin.filterField,
        // dependencyArray: filterConsts.basin.dependencyArray,
    },
    {
        label: "Field",
        type: "autocomplete",
        key: "field",
        edit: true,
        // mongoKey: 'field',
        // filterKey: filterConsts.field.filterKey,
        // filterKey: filterConsts.field.filterKey,
        // dependencyArray: filterConsts.field.dependencyArray,
    },
];

export default tableData;
