const Agreement = [
  {
    label: "Recording Date",
    mapped_key: "",
    required: true,
    actual_key: "recordedDate",
  },
  {
    label: "Book",
    mapped_key: "",
    required: true,
    actual_key: "recordedBook",
  },
  {
    label: "Page",
    mapped_key: "",
    required: true,
    actual_key: "recordedPage",
  },
  {
    label: "Instrument #",
    mapped_key: "",
    required: true,
    actual_key: "recordedInstrumentNumber",
  },
  {
    label: "Agreement System ID",
    mapped_key: "",
    required: true,
    actual_key: "_id",
  },
  {
    label: "Agreement Number",
    mapped_key: "",
    required: true,
    actual_key: "agreementNumber",
  },
  {
    label: "Agreement Name",
    mapped_key: "",
    required: true,
    actual_key: "agreementName",
  },
  {
    label: "Agreement Type",
    mapped_key: "",
    required: true,
    actual_key: "agreementType",
  },
  {
    label: "Agreement Subtype",
    mapped_key: "",
    required: false,
    actual_key: "agreementSubtype",
  },
  {
    label: "Rights Type",
    mapped_key: "",
    required: false,
    actual_key: "rightsType",
  },
  {
    label: "Agreement Status",
    mapped_key: "",
    required: false,
    actual_key: "agreementStatus",
  },
  {
    label: "Lessor(Grantor)",
    mapped_key: "",
    required: false,
    actual_key: "grantor",
  },
  {
    label: "Lessee(Grantee)",
    mapped_key: "",
    required: false,
    actual_key: "grantee",
  },
  {
    label: "Agreement Date",
    mapped_key: "",
    required: false,
    actual_key: "agreementDate",
  },
  {
    label: "Effective Date",
    mapped_key: "",
    required: false,
    actual_key: "effectiveDate",
  },
  {
    label: "Term(months)",
    mapped_key: "",
    required: false,
    actual_key: "agreementTerm",
  },
  {
    label: "Expiration Date",
    mapped_key: "",
    required: true,
    actual_key: "expirationDate",
  },
  {
    label: "Bonus Payment",
    mapped_key: "",
    required: true,
    actual_key: "bounusPayment",
  },
  {
    label: "Approval Status",
    mapped_key: "",
    required: true,
    actual_key: "approvalStatus",
  },
  {
    label: "Extension Date",
    mapped_key: "",
    required: true,
    actual_key: "extensionDate",
  },
  {
    label: "Description",
    mapped_key: "",
    required: true,
    actual_key: "metaDescription",
  },
  {
    label: "Acquisition ID",
    mapped_key: "",
    required: true,
    actual_key: "acquisitionID",
  },
  {
    label: "Acquisition Date",
    mapped_key: "",
    required: true,
    actual_key: "acquisitionDate",
  },
  {
    label: "Prospect",
    mapped_key: "",
    required: true,
    actual_key: "prospectID",
  },
  {
    label: "Internal Company",
    mapped_key: "",
    required: true,
    actual_key: "internalCompany",
  },
  {
    label: "State",
    mapped_key: "",
    required: true,
    actual_key: "state",
  },
  {
    label: "County",
    mapped_key: "",
    required: true,
    actual_key: "county",
  },
];
export default Agreement;
