const CHECKDETAILSENERGY = [
	{
		// unmapped
		label: 'UID',
		mapped_key: 'Line Number',
		required: true,
		actual_key: 'lineNumber',
		showAsSample: false,
	},
	{
		// unmapped
		label: 'Payor',
		mapped_key: '',
		required: false,
		actual_key: 'check.payor.name',
		showAsSample: false,
	},
	{
		label: 'Check Number',
		mapped_key: '',
		required: false,
		actual_key: 'check.checkNumber',
		showAsSample: false,
	},
	{
		label: 'Check Amount',
		mapped_key: '',
		required: false,
		actual_key: 'check.checkAmount',
		showAsSample: false,
	},
	{
		label: 'Check Date',
		mapped_key: '',
		required: false,
		actual_key: 'check.checkDate',
		showAsSample: false,
	},
	{
		// unmapped
		label: 'M1 Property ID',
		mapped_key: '',
		required: false,
		actual_key: 'property._id',
	},
	{
		// unmapped
		label: 'Payor Prop #',
		mapped_key: '',
		required: false,
		actual_key: 'property.purchaserNumber',
	},
	{
		label: 'Operator CC',
		mapped_key: 'Payor Prop #',
		required: false,
		actual_key: 'property.purchaserNumber',
	},
	{
		// unmapped
		label: 'Accounting Ref ID',
		mapped_key: '',
		required: false,
		actual_key: 'property.internalID',
	},
	{
		// unmapped
		label: 'Property Name',
		mapped_key: '',
		required: false,
		actual_key: 'property.name',
	},
	{
		label: 'Operator Name',
		mapped_key: '',
		required: false,
		actual_key: 'property.operator',
	},
	{
		label: 'Owner Number',
		mapped_key: '',
		required: false,
		actual_key: 'check.payee.number',
		showAsSample: false,
	},
	{
		label: 'Owner Name',
		mapped_key: '',
		required: false,
		actual_key: 'check.payee.name',
		showAsSample: false,
	},
	{
		label: 'Owner Percent',
		mapped_key: '',
		required: false,
		actual_key: 'check.payee.percent',
		showAsSample: false,
	},
	{
		label: 'Distribution Percent',
		mapped_key: '',
		required: false,
		actual_key: 'check.payee.distributionPercent',
		showAsSample: false,
	},
	{
		label: 'Prod Date',
		mapped_key: 'Sales Date',
		required: false,
		actual_key: 'date',
	},
	{
		label: 'BTU Factor',
		mapped_key: '',
		required: false,
		actual_key: 'BTU',
	},
	{
		// Prod Date
		label: 'Sales Date',
		mapped_key: '',
		required: true,
		actual_key: 'date',
	},
	{
		label: 'Product Code Description',
		mapped_key: '',
		required: false,
		actual_key: 'product',
	},
	{
		label: 'Property Description',
		mapped_key: '',
		required: false,
		actual_key: 'property.description',
	},
	{
		// unmapped
		label: 'Decimal Interest',
		mapped_key: '',
		required: false,
		actual_key: 'disbursement',
	},
	{
		label: 'Interest Type',
		mapped_key: '',
		required: false,
		actual_key: 'interestType',
	},
	{
		label: 'Price',
		mapped_key: '',
		required: false,
		actual_key: 'price',
	},
	{
		label: 'Gross Volume',
		mapped_key: '',
		required: false,
		actual_key: 'grossPropertyVolume',
	},
	{
		label: 'Gross Value',
		mapped_key: '',
		required: false,
		actual_key: 'grossPropertyValue',
	},
	{
		label: 'Gross Taxes',
		mapped_key: '',
		required: false,
		actual_key: 'grossPropertyTaxes',
	},
	{
		label: 'Gross Deducts',
		mapped_key: '',
		required: false,
		actual_key: 'grossPropertyDeducts',
	},
	{
		label: 'Owner Volume',
		mapped_key: '',
		required: false,
		actual_key: 'grossOwnerVolume',
	},
	{
		label: 'Owner Value',
		mapped_key: '',
		required: false,
		actual_key: 'grossOwnerValue',
	},
	{
		label: 'Owner Taxes',
		mapped_key: '',
		required: false,
		actual_key: 'ownerTax',
	},
	{
		label: 'Owner Deducts',
		mapped_key: '',
		required: false,
		actual_key: 'ownerDeducts',
	},

	// Tax keys
	{
		label: 'Tax Type',
		mapped_key: '',
		required: false,
		actual_key: 'taxType',
	},
	{
		label: 'Gross Tax',
		mapped_key: '',
		required: false,
		actual_key: 'grossTax',
	},
	{
		label: 'Net Tax',
		mapped_key: '',
		required: false,
		actual_key: 'netTax',
	},

	// Deduct keys
	{
		label: 'Deduct Type',
		mapped_key: '',
		required: false,
		actual_key: 'deductType',
	},
	{
		label: 'Gross Deduct',
		mapped_key: '',
		required: false,
		actual_key: 'grossDeduct',
	},
	{
		label: 'Net Deduct',
		mapped_key: '',
		required: false,
		actual_key: 'netDeduct',
	},

	{
		label: 'Owner Net Value',
		mapped_key: '',
		required: false,
		actual_key: 'netOwnerValue',
	},
	{
		label: 'Net Value',
		mapped_key: '',
		required: false,
		actual_key: 'netValue',
	},

	{
		// unmapped
		label: 'Line Number',
		mapped_key: '',
		required: true,
		actual_key: 'lineNumber',
		showAsSample: false,
	},

	{
		label: 'Detail Line Notation',
		mapped_key: '',
		required: false,
		actual_key: 'detailLineNotation',
	},
];

// export default [
//     {
//         label: "Sender",
//         mapped_key: "",
//         required: false,
//         actual_key: "check.payor.name",
//     },
//     {
//         label: "Check#",
//         mapped_key: "",
//         required: false,
//         actual_key: "check.checkNumber",
//     },
//     {
//         label: "Property#",
//         mapped_key: "",
//         required: false,
//         actual_key: "property.number",
//     },
//     {
//         label: "CheckDate",
//         mapped_key: "",
//         required: false,
//         actual_key: "check.checkDate",
//     },
//     {
//         label: "PropertyName",
//         mapped_key: "",
//         required: false,
//         actual_key: "property.name",
//     },
//     {
//         label: "Owner#",
//         mapped_key: "",
//         required: false,
//         actual_key: "check.payee.number",
//     },
//     {
//         label: "ToProdDate",
//         mapped_key: "",
//         required: false,
//         actual_key: "ToProdDate",
//     },
//     {
//         label: "FromProdDate",
//         mapped_key: "",
//         required: false,
//         actual_key: "FromProdDate",
//     },
//     {
//         label: "GrsVol",
//         mapped_key: "",
//         required: false,
//         actual_key: "grossPropertyVolume",
//     },
//     {
//         label: "OwnGrsVal",
//         mapped_key: "",
//         required: false,
//         actual_key: "grossOwnerValue",
//     },
//     {
//         label: "GrsSevTax",
//         mapped_key: "",
//         required: false,
//         actual_key: "propertyTax",
//     },
//     {
//         label: "OwnDec",
//         mapped_key: "",
//         required: false,
//         actual_key: "disbursement",
//     },
//     {
//         label: "NetVal",
//         mapped_key: "",
//         required: false,
//         actual_key: "netPropertyValue",
//     },
//     {
//         label: "GrsDeduct",
//         mapped_key: "",
//         required: false,
//         actual_key: "propertyDeducts",
//     },
//     {
//         label: "OwnDeduct",
//         mapped_key: "",
//         required: false,
//         actual_key: "ownerDeducts",
//     },
//     {
//         label: "TranDate",
//         mapped_key: "",
//         required: false,
//         actual_key: "date",
//     },
//     {
//         label: "IntType",
//         mapped_key: "",
//         required: false,
//         actual_key: "interestTypeCode",
//     },
//     {
//         label: "UnitPrice",
//         mapped_key: "",
//         required: false,
//         actual_key: "price",
//     },
//     {
//         label: "ProdCode",
//         mapped_key: "",
//         required: false,
//         actual_key: "productCode",
//     },
//     {
//         label: "TotalProd",
//         mapped_key: "",
//         required: false,
//         actual_key: "TotalProd",
//     },
//     {
//         label: "GrsNetVal",
//         mapped_key: "",
//         required: false,
//         actual_key: "GrsNetVal",
//     },
//     {
//         label: "OwnNetVal",
//         mapped_key: "",
//         required: false,
//         actual_key: "netOwnerValue",
//     },
//     {
//         label: "OwnSevTax",
//         mapped_key: "",
//         required: false,
//         actual_key: "ownerTax",
//     },
//     {
//         label: "OwnNetVol",
//         mapped_key: "",
//         required: false,
//         actual_key: "netOwnerVolume",
//     },
//     {
//         label: "OwnVol",
//         mapped_key: "",
//         required: false,
//         actual_key: "grossOwnerVolume",
//     },
//     {
//         label: "GrsVal",
//         mapped_key: "",
//         required: false,
//         actual_key: "grossPropertyValue",
//     },
//     {
//         label: "OwnShareLNV",
//         mapped_key: "",
//         required: false,
//         actual_key: "OwnShareLNV",
//     },
//     {
//         label: "BTU",
//         mapped_key: "",
//         required: false,
//         actual_key: "BTU",
//     },
//     {
//         label: "ProductionUnit",
//         mapped_key: "",
//         required: false,
//         actual_key: "ProductionUnit",
//     },
//     {
//         label: "[EMPTY COLUMN]",
//         mapped_key: "",
//         required: false,
//         actual_key: "[EMPTY COLUMN]",
//     },
//     {
//         label: "DecFlag",
//         mapped_key: "",
//         required: false,
//         actual_key: "DecFlag",
//     },
//     {
//         label: "MappedIntType",
//         mapped_key: "",
//         required: false,
//         actual_key: "interestType",
//     },
//     {
//         label: "MappedTranCode2",
//         mapped_key: "",
//         required: false,
//         actual_key: "MappedTranCode2",
//     },
//     {
//         label: "TranCode2",
//         mapped_key: "",
//         required: false,
//         actual_key: "TranCode2",
//     },
//     {
//         label: "OwnGrsVal2",
//         mapped_key: "",
//         required: false,
//         actual_key: "OwnGrsVal2",
//     },
//     {
//         label: "OwnSevTax2",
//         mapped_key: "",
//         required: false,
//         actual_key: "OwnSevTax2",
//     },
//     {
//         label: "Line#",
//         mapped_key: "",
//         required: false,
//         actual_key: "lineNumber",
//     },
//     {
//         label: "MappedTranCode1",
//         mapped_key: "",
//         required: false,
//         actual_key: "MappedTranCode1",
//     },
//     {
//         label: "MappedPropertyName",
//         mapped_key: "",
//         required: false,
//         actual_key: "MappedPropertyName",
//     },
//     {
//         label: "TranCode1",
//         mapped_key: "",
//         required: false,
//         actual_key: "TranCode1",
//     },
//     {
//         label: "MappedProperty#",
//         mapped_key: "",
//         required: false,
//         actual_key: "MappedProperty#",
//     },
//     {
//         label: "MappedProdCode",
//         mapped_key: "",
//         required: false,
//         actual_key: "product",
//     },
//     {
//         label: "RoyaltyAgreement",
//         mapped_key: "",
//         required: false,
//         actual_key: "RoyaltyAgreement",
//     },
//     {
//         label: "MappedOwnDec",
//         mapped_key: "",
//         required: false,
//         actual_key: "MappedOwnDec",
//     },
//     {
//         label: "DivOfInterest",
//         mapped_key: "",
//         required: false,
//         actual_key: "divisionOfInterestCode",
//     },
//     {
//         label: "Comment",
//         mapped_key: "",
//         required: false,
//         actual_key: "comments",
//     },
//     {
//         label: "Tags",
//         mapped_key: "",
//         required: false,
//         actual_key: "check.tags"
//     },
// ];

const checkDetailsKeys = [
	{
		label: 'UID',
		mapped_key: 'Line Number',
		required: true,
		actual_key: 'lineNumber',
		showAsSample: false,
	},
	{
		label: 'Payor',
		mapped_key: '',
		required: false,
		actual_key: 'check.payor.name',
		showAsSample: false,
	},
	{
		label: 'Check Number',
		mapped_key: '',
		required: false,
		actual_key: 'check.checkNumber',
		showAsSample: false,
	},
	{
		label: 'Check Amount',
		mapped_key: '',
		required: false,
		actual_key: 'check.checkAmount',
		showAsSample: false,
	},
	{
		label: 'Check Date',
		mapped_key: '',
		required: false,
		actual_key: 'check.checkDate',
		showAsSample: false,
	},
	{
		label: 'M1 Property ID',
		mapped_key: '',
		required: false,
		actual_key: 'property._id',
	},
	{
		label: 'Payor Prop #',
		mapped_key: '',
		required: false,
		actual_key: 'property.purchaserNumber',
	},
	{
		label: 'Operator Prop #',
		mapped_key: '',
		required: false,
		actual_key: 'property.number',
	},
	{
		label: 'Accounting Ref ID',
		mapped_key: '',
		required: false,
		actual_key: 'property.internalID',
	},
	{
		label: 'Property Name',
		mapped_key: '',
		required: false,
		actual_key: 'property.name',
	},
	{
		label: 'Operator Name',
		mapped_key: '',
		required: false,
		actual_key: 'property.operator',
	},
	{
		label: 'Owner Number',
		mapped_key: '',
		required: false,
		actual_key: 'check.payee.number',
		showAsSample: false,
	},
	{
		label: 'Owner Name',
		mapped_key: '',
		required: false,
		actual_key: 'check.payee.name',
		showAsSample: false,
	},
	{
		label: 'Sales Date',
		mapped_key: '',
		required: true,
		actual_key: 'date',
	},
	{
		label: 'Product Code',
		mapped_key: '',
		required: false,
		actual_key: 'product',
	},
	{
		label: 'Property Description',
		mapped_key: '',
		required: false,
		actual_key: 'property.description',
	},
	{
		label: 'Decimal Interest',
		mapped_key: '',
		required: false,
		actual_key: 'disbursement',
	},
	{
		label: 'Interest Type',
		mapped_key: '',
		required: false,
		actual_key: 'interestType',
	},
	{
		label: 'Avg Price',
		mapped_key: '',
		required: false,
		actual_key: 'price',
	},
	{
		label: 'Property Gross Volume',
		mapped_key: '',
		required: false,
		actual_key: 'grossPropertyVolume',
	},
	{
		label: 'Property Gross Revenue',
		mapped_key: '',
		required: false,
		actual_key: 'grossPropertyValue',
	},
	{
		label: 'Owner Volume',
		mapped_key: '',
		required: false,
		actual_key: 'grossOwnerVolume',
	},
	{
		label: 'Owner Value',
		mapped_key: '',
		required: false,
		actual_key: 'grossOwnerValue',
	},
	{
		label: 'Owner Tax Amount',
		mapped_key: '',
		required: false,
		actual_key: 'ownerTax',
	},
	{
		label: 'Tax Type',
		mapped_key: '',
		required: false,
		actual_key: 'taxType',
	},
	{
		label: 'Owner Deduct Amount',
		mapped_key: '',
		required: false,
		actual_key: 'ownerDeducts',
	},
	{
		label: 'Deduct Code',
		mapped_key: '',
		required: false,
		actual_key: 'deductType',
	},
	{
		label: 'Owner Net Revenue',
		mapped_key: '',
		required: false,
		actual_key: 'netOwnerValue',
	},

	{
		label: 'Line Number',
		mapped_key: '',
		required: true,
		actual_key: 'lineNumber',
		showAsSample: false,
	},

	// {
	//     label: "Purchaser Name",
	//     mapped_key: "",
	//     required: false,
	//     actual_key: "property.purchaser.name",
	// },
];

export { CHECKDETAILSENERGY };
export default checkDetailsKeys;
