export default [
    {
        label: "Sender",
        mapped_key: "",
        required: false,
        actual_key: "check.payor.name",
    },
    {
        label: "Check#",
        mapped_key: "",
        required: false,
        actual_key: "check.checkNumber",
    },
    {
        label: "Property#",
        mapped_key: "",
        required: false,
        actual_key: "property.number",
    },
    {
        label: "CheckDate",
        mapped_key: "",
        required: false,
        actual_key: "check.checkDate",
    },
    {
        label: "PropertyName",
        mapped_key: "",
        required: false,
        actual_key: "property.name",
    },
    {
        label: "Owner#",
        mapped_key: "",
        required: false,
        actual_key: "check.payee.number",
    },
    {
        label: "ToProdDate",
        mapped_key: "",
        required: false,
        actual_key: "ToProdDate",
    },
    {
        label: "FromProdDate",
        mapped_key: "",
        required: false,
        actual_key: "FromProdDate",
    },
    {
        label: "GrsVol",
        mapped_key: "",
        required: false,
        actual_key: "grossPropertyVolume",
    },
    {
        label: "OwnGrsVal",
        mapped_key: "",
        required: false,
        actual_key: "grossOwnerValue",
    },
    {
        label: "GrsSevTax",
        mapped_key: "",
        required: false,
        actual_key: "propertyTax",
    },
    {
        label: "OwnDec",
        mapped_key: "",
        required: false,
        actual_key: "disbursement",
    },
    {
        label: "NetVal",
        mapped_key: "",
        required: false,
        actual_key: "netPropertyValue",
    },
    {
        label: "GrsDeduct",
        mapped_key: "",
        required: false,
        actual_key: "propertyDeducts",
    },
    {
        label: "OwnDeduct",
        mapped_key: "",
        required: false,
        actual_key: "ownerDeducts",
    },
    {
        label: "TranDate",
        mapped_key: "",
        required: false,
        actual_key: "date",
    },
    {
        label: "IntType",
        mapped_key: "",
        required: false,
        actual_key: "interestTypeCode",
    },
    {
        label: "UnitPrice",
        mapped_key: "",
        required: false,
        actual_key: "price",
    },
    {
        label: "ProdCode",
        mapped_key: "",
        required: false,
        actual_key: "productCode",
    },
    {
        label: "TotalProd",
        mapped_key: "",
        required: false,
        actual_key: "TotalProd",
    },
    {
        label: "GrsNetVal",
        mapped_key: "",
        required: false,
        actual_key: "GrsNetVal",
    },
    {
        label: "OwnNetVal",
        mapped_key: "",
        required: false,
        actual_key: "netOwnerValue",
    },
    {
        label: "OwnSevTax",
        mapped_key: "",
        required: false,
        actual_key: "ownerTax",
    },
    {
        label: "OwnNetVol",
        mapped_key: "",
        required: false,
        actual_key: "netOwnerVolume",
    },
    {
        label: "OwnVol",
        mapped_key: "",
        required: false,
        actual_key: "grossOwnerVolume",
    },
    {
        label: "GrsVal",
        mapped_key: "",
        required: false,
        actual_key: "grossPropertyValue",
    },
    {
        label: "OwnShareLNV",
        mapped_key: "",
        required: false,
        actual_key: "OwnShareLNV",
    },
    {
        label: "BTU",
        mapped_key: "",
        required: false,
        actual_key: "BTU",
    },
    {
        label: "ProductionUnit",
        mapped_key: "",
        required: false,
        actual_key: "ProductionUnit",
    },
    {
        label: "[EMPTY COLUMN]",
        mapped_key: "",
        required: false,
        actual_key: "[EMPTY COLUMN]",
    },
    {
        label: "DecFlag",
        mapped_key: "",
        required: false,
        actual_key: "DecFlag",
    },
    {
        label: "MappedIntType",
        mapped_key: "",
        required: false,
        actual_key: "interestType",
    },
    {
        label: "MappedTranCode2",
        mapped_key: "",
        required: false,
        actual_key: "MappedTranCode2",
    },
    {
        label: "TranCode2",
        mapped_key: "",
        required: false,
        actual_key: "TranCode2",
    },
    {
        label: "OwnGrsVal2",
        mapped_key: "",
        required: false,
        actual_key: "OwnGrsVal2",
    },
    {
        label: "OwnSevTax2",
        mapped_key: "",
        required: false,
        actual_key: "OwnSevTax2",
    },
    {
        label: "Line#",
        mapped_key: "",
        required: false,
        actual_key: "lineNumber",
    },
    {
        label: "MappedTranCode1",
        mapped_key: "",
        required: false,
        actual_key: "MappedTranCode1",
    },
    {
        label: "MappedPropertyName",
        mapped_key: "",
        required: false,
        actual_key: "MappedPropertyName",
    },
    {
        label: "TranCode1",
        mapped_key: "",
        required: false,
        actual_key: "TranCode1",
    },
    {
        label: "MappedProperty#",
        mapped_key: "",
        required: false,
        actual_key: "MappedProperty#",
    },
    {
        label: "MappedProdCode",
        mapped_key: "",
        required: false,
        actual_key: "product",
    },
    {
        label: "RoyaltyAgreement",
        mapped_key: "",
        required: false,
        actual_key: "RoyaltyAgreement",
    },
    {
        label: "MappedOwnDec",
        mapped_key: "",
        required: false,
        actual_key: "MappedOwnDec",
    },
    {
        label: "DivOfInterest",
        mapped_key: "",
        required: false,
        actual_key: "divisionOfInterestCode",
    },
    {
        label: "Comment",
        mapped_key: "",
        required: false,
        actual_key: "comments",
    }
];