export default [
    {
        label: "Property Number",
        mapped_key: "",
        required: false,
        actual_key: "property.number",
    },
    {
        label: "Property Name",
        mapped_key: "",
        required: false,
        actual_key: "property.name",
    },
    {
        label: "Property State",
        mapped_key: "",
        required: false,
        actual_key: "property.state",
    },
    {
        label: "Property County",
        mapped_key: "",
        required: false,
        actual_key: "property.county",
    },
    {
        label: "Property Status",
        mapped_key: "",
        required: false,
        actual_key: "property.status",
    },
    {
        label: "Property Legal Description",
        mapped_key: "",
        required: false,
        actual_key: "property.legalDescription",
    },
    {
        label: "Property Tags",
        mapped_key: "",
        required: false,
        actual_key: "property.tags",
    },
    {
        label: "Div Order Date",
        mapped_key: "",
        required: false,
        actual_key: "property.documentDate",
    },
    {
        label: "Operator Name",
        mapped_key: "",
        required: false,
        actual_key: "property.operator.name",
    },
    {
        label: "Owner Number",
        mapped_key: "",
        required: false,
        actual_key: "number",
    },
    {
        label: "Owner Contact ID",
        mapped_key: "",
        required: false,
        actual_key: "_id",
    },
    {
        label: "Owner Name",
        mapped_key: "",
        required: false,
        actual_key: "entityDetail.name",
    },
    {
        label: "Owner Primary Address",
        mapped_key: "",
        required: false,
        actual_key: "entityDetail.address1",
    },
    {
        label: "Owner City",
        mapped_key: "",
        required: false,
        actual_key: "entityDetail.city",
    },
    {
        label: "Owner State",
        mapped_key: "",
        required: false,
        actual_key: "entityDetail.state",
    },
    {
        label: "Owner Zip Code",
        mapped_key: "",
        required: false,
        actual_key: "entityDetail.zip",
    },
    {
        label: "Interest Type",
        mapped_key: "",
        required: false,
        actual_key: "propertyDescriptor.interestType",
    },
    {
        label: "Interest Amount",
        mapped_key: "",
        required: false,
        actual_key: "propertyDescriptor.interestAmount",
    },
    {
        label: "Effective Date",
        mapped_key: "",
        required: false,
        actual_key: "propertyDescriptor.effectiveDate",
    },
    {
        label: "Interest Status",
        mapped_key: "",
        required: false,
        actual_key: "propertyDescriptor.status",
    },
    {
        label: "Cost Free",
        mapped_key: "",
        required: false,
        actual_key: "propertyDescriptor.costFree",
    },
    {
        label: "Associated Well API Numbers",
        mapped_key: "",
        required: false,
        actual_key: "property.wells",
    },
    {
        label: "Approver",
        mapped_key: "",
        required: false,
        actual_key: "property.approver",
    },
];