export default [
    {
        label: "Property Number",
        mapped_key: "",
        required: false,
        actual_key: "property.number",
    },
    {
        label: "Property Name",
        mapped_key: "",
        required: false,
        actual_key: "property.name",
    },
    {
        label: "Internal ID",
        mapped_key: "",
        required: false,
        actual_key: "property.internalID",
    },
    {
        label: "Internal Company",
        mapped_key: "",
        required: false,
        actual_key: "property.internalCompany",
    },
    {
        label: "Acquisition ID",
        mapped_key: "",
        required: false,
        actual_key: "property.acquisitionID",
    },
    {
        label: "Prospect",
        mapped_key: "",
        required: false,
        actual_key: "property.prospectID",
    },
    {
        label: "Property State",
        mapped_key: "",
        required: false,
        actual_key: "property.state",
    },
    {
        label: "Property County",
        mapped_key: "",
        required: false,
        actual_key: "property.county",
    },
    {
        label: "Property Status",
        mapped_key: "",
        required: false,
        actual_key: "property.status",
    },
    {
        label: "Property Legal Description",
        mapped_key: "",
        required: false,
        actual_key: "property.legalDescription",
    },
    {
        label: "Property Tags",
        mapped_key: "",
        required: false,
        actual_key: "property.tags",
    },
    {
        label: "Document Date",
        mapped_key: "",
        required: false,
        actual_key: "property.documentDate",
    },
    {
        label: "DO Status",
        mapped_key: "",
        required: false,
        actual_key: "property.divOrderStatus",
    },
    {
        label: "Operator Name",
        mapped_key: "",
        required: false,
        actual_key: "property.operator.name",
    },
    {
        label: "Owner Number",
        mapped_key: "",
        required: false,
        actual_key: "property.ownerNumber",
    },
    {
        label: "Owner Contact ID",
        mapped_key: "",
        required: false,
        actual_key: "_id",
    },
    {
        label: "Owner Name",
        mapped_key: "",
        required: false,
        actual_key: "entityDetail.name",
    },
    {
        label: "Owner Primary Address",
        mapped_key: "",
        required: false,
        actual_key: "entityDetail.address1",
    },
    {
        label: "Owner City",
        mapped_key: "",
        required: false,
        actual_key: "entityDetail.city",
    },
    {
        label: "Owner State",
        mapped_key: "",
        required: false,
        actual_key: "entityDetail.state",
    },
    {
        label: "Owner Zip Code",
        mapped_key: "",
        required: false,
        actual_key: "entityDetail.zip",
    },
    {
        label: "Interest Type",
        mapped_key: "",
        required: false,
        actual_key: "propertyInterest.interestType",
    },
    {
        label: "Interest Amount",
        mapped_key: "",
        required: false,
        actual_key: "propertyInterest.interestAmount",
    },
    {
        label: "Effective Date",
        mapped_key: "",
        required: false,
        actual_key: "propertyInterest.effectiveDate",
    },
    {
        label: "Interest Status",
        mapped_key: "",
        required: false,
        actual_key: "propertyInterest.status",
    },
    {
        label: "Cost Free",
        mapped_key: "",
        required: false,
        actual_key: "propertyInterest.costFree",
    },
    {
        label: "Associated Well API Numbers",
        mapped_key: "",
        required: false,
        actual_key: "wellsApiNumbers",
    },
    {
        label: "Approver",
        mapped_key: "",
        required: false,
        actual_key: "property.approver",
    },
];