import gql from 'graphql-tag';

export const UPDATE_CONTACT_PURCHASE_DATA = gql`
	mutation updateContactPurchaseData($purchaseData: JSON, $isDialpadEnabled: Boolean) {
		updateContactPurchaseData(purchaseData: $purchaseData, isDialpadEnabled: $isDialpadEnabled) {
			age
			bankruptcy
			contactId
			currentAddress
			currentAddressDateRange
			dataProvider
			deceased
			firstName
			fullName
			lastName
			lien
			phone1
			phone1LastSeen
			phone1Type
			phone1Status
			phone2
			phone2LastSeen
			phone2Type
			phone2Status
			phone3
			phone3LastSeen
			phone3Type
			phone3Status
			phone4
			phone4LastSeen
			phone4Type
			phone4Status
			phone5
			phone5LastSeen
			phone5Type
			phone5Status
			pid
			previousAddress1
			previousAddress1DateRange
			referenceId
			relative1Age
			relative1FirstName
			relative1LastName
			relative1Phone1
			relative1Phone2
			relative1Phone3
			relative2Age
			relative2FirstName
			relative2LastName
			relative2Phone1
			relative2Phone2
			relative3Age
			relative3FirstName
			relative3LastName
			relative3Phone1
			relative3Phone2
			relative3Phone3
			relative4Age
			relative4FirstName
			relative4LastName
			relative4Phone1
			relative4Phone2
			relative4Phone3
			relative5Age
			relative5FirstName
			relative5LastName
			relative5Phone1
			relative5Phone2
			relative5Phone3
			sqlContactGuid
			sysDateTime
		}
	}
`;
